easyconfigs/c/CIRI-long/CIRI-long-1.1.0-foss-2021b.eb, easyconfigs/p/pyspoa/pyspoa-0.0.8-GCC-11.2.0.eb, easyconfigs/p/python-Levenshtein/python-Levenshtein-0.12.2-foss-2021b.eb, easyconfigs/s/spoa/spoa-4.0.7-GCC-11.2.0.eb
For INC1267960- `CIRI-long-1.1.0-foss-2021b.eb`
Also requires:
`Pyspoa-0.0.8-GCC-11.2.0.eb` - pulled from upstream
`python-Levenshtein-0.12.2-foss-2021b.eb` - pulled from upstream and bumped to latest available release
`spoa-4.0.7-GCC-11.2.0.eb` - pulled from upstream
Default:
=> CIRI-long 1.1.0

easyconfigs/a/alsa-lib/alsa-lib-1.2.7.2.eb, easyconfigs/m/MATLAB/MATLAB-2022a.eb
For INC1271218 - `MATLAB-2022a.eb`
Requires: https://gitlab.bham.ac.uk/res-comp-team/bear-license-servers/-/merge_requests/8
N.B. the necessary env vars will need setting in order to perform the install
Default:
=> MATLAB 2022a

easyconfigs/m/MNE-Python/MNE-Python-1.1.1-foss-2021b.eb
For INC1300320 - `MNE-Python-1.1.1-foss-2021b.eb`
N.B. not using our _lxml_ module because MNE needs a newer version and our module is only a dependency for a couple of others so it seems safe to handle it as an extension instead. (It necessitates the inclusion of the deps on lines 19 & 20.)
Default:
=> mne 1.1.1 easyconf

easyconfigs/b/BEAR-R-bio/BEAR-R-bio-2021b-foss-2021b-R-4.2.0.eb, easyconfigs/m/maftools/maftools-2.12.0-foss-2021b-R-4.2.0.eb
For INC1312505- `maftools-2.12.0-foss-2021b-R-4.2.0.eb`
_INC1312505 is primarily concerned with usage of maftools within the CCB MSc RStudio (2022) environment_
_Shout at me if there's anything missing from this PR to get it working for the CCB_
Default:
=> maftools + add to BIO meta package 

easyconfigs/m/modbam2bed/modbam2bed-0.7.0-GCC-11.2.0.eb
For INC1338954 - `modbam2bed-0.7.0-GCC-11.2.0.eb`
- this is only the build of the cmdline component not the python module (as requested by the user)
- i've not included the mem_check test as it stops eb's build process completing successfully
Default:
=> modbam2bed

easyconfigs/o/OSU-Micro-Benchmarks/OSU-Micro-Benchmarks-5.7.1-iimpi-2021b.eb
For consistency - `OSU-Micro-Benchmarks-5.7.1-iimpi-2021b.eb`
Default:
=> OSU iimpi 2021b to match the other versions

easyconfigs/c/CellRanger/CellRanger-7.1.0.eb
For INC1371944 - `CellRanger-7.1.0.eb`
- Slight change from upstream as the sanity check currently requires `export MRO_DISK_SPACE_CHECK=disable` to avoid failing the available disk space check.
Default:
=> CellRanger 7.1.0 (2022a)

easyconfigs/b/BEAR-R-bio/BEAR-R-bio-2021b-MSc-foss-2021b-R-4.2.0.eb, easyconfigs/m/mofapy2/mofapy2-0.6.7-foss-2021b.eb
For INC1370279 - the associated MOFA2 requires an older mofapy2.
`mofapy2-0.6.7-foss-2021b.eb`:
rebuild `BEAR-R-bio-2021b-MSc-foss-2021b-R-4.2.0.eb`:
=> switch to mofapy2 0.6.7

easyconfigs/g/Gaussian/Gaussian-16.C.02-AVX2.eb
For INC1356942 - `Gaussian-16.C.02-AVX2.eb`
Default:
N.B. as this is a pre-compiled AVX2 build I'm excluding:
* EL8-haswell
=> Gaussian 16 easyconf

LICENSE
Using GPLv2 instead of GPLv3 so that we match the EasyBuild repo for the purposes of upstreaming content.
=> Use GPLv2 licence

easyconfigs/m/mozbc/mozbc-20230507-foss-2022a.eb
For INC1372511 - `mozbc-20230507-foss-2022a.eb`
Default:
=> mozbc WRF preprocessor

easyconfigs/b/BEAR-R-bio/BEAR-R-bio-2022b-foss-2022b-R-4.3.1.eb
For INC1396312 - `BEAR-R-bio-2022b-foss-2022b-R-4.3.1.eb`
This is so we can add it to the Portal. Sorting out the extra easyconfigs for the MSc will happen in #211, hence the commented out older versions in here.
Default:
=> initial BEAR R bio

easyconfigs/m/mne-connectivity/mne-connectivity-0.5.0-foss-2021b.eb
For INC1427684 - `mne-connectivity-0.5.0-foss-2021b.eb`
* Uses newer version of netcdf-python - supplied as an extension + supporting dep.
`time eb mne-connectivity-0.5.0-foss-2021b.eb --rebuild --force -Tr`
Default:
=> mne-connectivity rebuild

easyconfigs/g/Guile/Guile-3.0.9-GCCcore-12.2.0.eb, easyconfigs/g/gc/gc-8.2.4-GCCcore-12.2.0.eb, easyconfigs/h/Harminv/Harminv-1.4.2-foss-2022b.eb, easyconfigs/l/libGDSII/libGDSII-0.21-GCCcore-12.2.0.eb, easyconfigs/l/libctl/libctl-4.5.1-GCCcore-12.2.0.eb, easyconfigs/l/libunistring/libunistring-1.1-GCCcore-12.2.0.eb, easyconfigs/m/MPB/MPB-1.11.1-foss-2022b.eb, easyconfigs/m/Meep/Meep-1.28.0-foss-2022b.eb
For IINC1439792 - `Meep-1.28.0-foss-2022b.eb`
**Deps:**
- `Guile-3.0.9-GCCcore-12.2.0.eb` - no upstream version for 2022b. Used same version as 2023a.
- `libunistring-1.1-GCCcore-12.2.0.eb` - Guile dependency. No upstream version for 2022b.
- `gc-8.2.4-GCCcore-12.2.0.eb` - Guile dependency. No upstream version for 2022b.
- `libctl-4.5.1-GCCcore-12.2.0.eb` - bumped our 2021b version. Still 4.5.1 still newest release.
- `Harminv-1.4.2-foss-2022b.eb` - installing newer point release
- `MPB-1.11.1-foss-2022b.eb` - bumped our 2021b version. 1.11.1 still newest release
- `libGDSII-0.21-GCCcore-12.2.0.eb` - bumped our 2021b version. 0.21 still newest release
Default:
=> Meep 1.28.0

easyconfigs/a/autograd/autograd-1.6.3-foss-2022b.eb, easyconfigs/m/Meep/Meep-1.28.0-foss-2022b.eb
For INC1439792
**Autograd:** - 1.6.3 dep requested by user (not required by Meep)
`eb autograd-1.6.3-foss-2022b.eb -Tr`
**Meep:** - rebuild 1.28.0 with the Autograd dep specified
`eb Meep-1.28.0-foss-2022b.eb --rebuild --force -Tr`
Default:
=> Autograd 1.6.3 +meep 1.28.0 rebuild

easyconfigs/n/NLopt/NLopt-2.7.1-foss-2022b-Python.eb
For INC1439792 - `NLopt-2.7.1-foss-2022b-Python.eb`
We need NLopt's Python Bindings. Like previous installs of this, i've done this in a separate easyconfig.
Default:
=> NLopt python bindings

easyconfigs/a/AMS/AMS-2023.104-gompi-2022a-openmpi.eb
For INC1416682 - `AMS-2023.104-gompi-2022a-openmpi.eb`
Version bumped with tweaks from upstream: https://github.com/easybuilders/easybuild-easyconfigs/blob/cad7b6668fe8d7b1dc1cc79be407b86c7ec9ce05/easybuild/easyconfigs/a/AMS/AMS-2023.101-iimpi-2022a-intelmpi.eb
Default:
=> AMS easyconf

easyconfigs/f/FSL/FSL-6.0.7.6.eb
For INC1446880 - `FSL-6.0.7.6.eb`
Based on Easyconf in PR https://github.com/easybuilders/easybuild-easyconfigs/pull/18697 but with version bump and using Mamba instead of Conda
Default:
=> FSL 6.0.7.6

easyconfigs/b/BAT/BAT-2.9.5-foss-2022b-R-4.3.1.eb, easyconfigs/h/hypvervolume/hypervolume-3.1.3-foss-2022b-R-4.3.1.eb, easyconfigs/p/phytools/phytools-2.0-3-foss-2022b-R-4.3.1.eb
For INC1450176 - we won't build Picante yet as the latest version hasn't been published to CRAN.
Please build in this order:
- `hypervolume-3.1.3-foss-2022b-R-4.3.1.eb`
- `phytools-2.0-3-foss-2022b-R-4.3.1.eb`
- `BAT-2.9.5-foss-2022b-R-4.3.1.eb `
Default:
=> BAT, hypervolume, phytools R pkgs for 2022b 

easyconfigs/p/PyTorch/PyTorch-2.0.1-foss-2022a-CUDA-11.7.0.eb
For INC1462866 - this change has already been deployed.
=> remove cuDNN dep from wheel version of PyTorch

easyblocks/cst.py, easyconfigs/c/CST-Studio-Suite/CST-Studio-Suite-2024.SP2-GCCcore-12.2.0-Java-17.eb
For INC1453699 - `CST-Studio-Suite-2024.SP2-GCCcore-12.2.0-Java-17.eb`
- The block is a copy of this one: https://github.com/bear-rsg/easybuild-easyblocks/blob/2021a/easybuild/easyblocks/c/cst.py
- The conf is a version (and Java) bump of this one: https://github.com/bear-rsg/easybuild-easyconfigs/blob/2021a/easybuild/easyconfigs/c/CST-Studio-Suite/CST-Studio-Suite-2022.SP4-GCCcore-10.3.0-Java-11.eb 
Default:
=> CST 2024 conf and block

easyconfigs/m/MATLAB/MATLAB-2023b-r6.eb
For INC1466080 - `MATLAB-2023b-r6.eb`
- Modified from upstream to install "Update 6" of R2023b.
Pass to @orbsmiv to install as he has the keys.
Default:
=> MATLAB R2023 Update 6

easyconfigs/d/DeepLabCut/DeepLabCut-2.3.6-foss-2022a-CUDA-11.7.0.eb, easyconfigs/d/DeepLabCut/DeepLabCut-2.3.6-foss-2022a.eb, easyconfigs/d/DeepLabCut/DeepLabCut-2.3.6_hpc-fix.patch
For INC1473012- `DeepLabCut-2.3.6-foss-2022a-CUDA-11.7.0.eb DeepLabCut-2.3.6-foss-2022a.eb`
Default:
**Note:** This is a rebuild. CUDA version is icelake only
The change is in place to stop it trying to install in the install directory, this has worked for my tests. It might require further editing from response from the user
=> Rebuild of DeepLabCut for INC1473012

easyconfigs/a/ASCAT/ASCAT-3.1.2-foss-2022b-R-4.3.1.eb, easyconfigs/b/Battenberg/Battenberg-2.2.9-foss-2022b-R-4.3.1.eb
For INC1459353 - `Battenberg-2.2.9-foss-2022b-R-4.3.1.eb`
`time eb Battenberg-2.2.9-foss-2022b-R-4.3.1.eb -Tr`
Other files:
+ ASCAT for 2022b and R4.3.1
Default:
=> Battenberg

easyconfigs/a/APR-util/APR-util-1.6.3-GCCcore-12.2.0.eb, easyconfigs/a/APR/APR-1.7.4-GCCcore-12.2.0.eb, easyconfigs/b/Boost/Boost-1.75.0-GCC-12.2.0.eb, easyconfigs/c/Cufflinks/Cufflinks-20190706-AM_INIT_AUTOMAKE.patch, easyconfigs/c/Cufflinks/Cufflinks-20190706-GCC-12.2.0.eb, easyconfigs/s/SCons/SCons-4.4.0_install_man_pages_correctly.patch, easyconfigs/s/SCons/SCons-4.5.2-GCCcore-12.2.0.eb, easyconfigs/s/Serf/Serf-1.3.10-GCCcore-12.2.0.eb, easyconfigs/s/Subversion/Subversion-1.12.0-no_swig.patch, easyconfigs/s/Subversion/Subversion-1.14.3-GCCcore-12.2.0.eb
For INC1468548 - `Cufflinks-20190706-GCC-12.2.0.eb`
- As upsteam (11.2.0 version) with only the deps version-bumped for 2022b/GCC-12.2.0.
- Note: uses older Boost version for compatibility with C++03
Default:
=> Cufflinks easyconf

easyconfigs/d/digitalDLSorteR/digitalDLSorteR-1.0.1-foss-2022b-R-4.3.1.eb
For INC1487268 - `digitalDLSorteR-1.0.1-foss-2022b-R-4.3.1.eb`
Default:
**Note:** This is a rebuild
=> Rebuild digitalDLSorteR with TensorFlow

easyconfigs/b/Barracuda_Virtual_Reactor/Barracuda_Virtual_Reactor-24.0.0-GCCcore-12.2.0.eb
For INC1503159 - `Barracuda_Virtual_Reactor-24.0.0-GCCcore-12.2.0.eb`
Version bump from `22.1.1`. No other changes.
Default:
=> Barracuda Virtual Reactor 24.0.0

easyconfigs/i/ipykernel/ipykernel-6.25.1-GCCcore-12.3.0.eb, easyconfigs/i/ipykernel/jupyter-core-5.3.1_fix_jupyter_path.patch
For internal - `ipykernel-6.25.1-GCCcore-12.3.0.eb`
Conf is a subset of the `jupyter-server-2.7.2-GCCcore-12.3.0.eb`
config file, providing the minimum required to run ipykernel.
Default:
=> ipykernel for JupyterLab app

easyconfigs/h/hdf5storage/hdf5storage-0.1.19-foss-2022b.eb
For INC1508572 - `hdf5storage-0.1.19-foss-2022b.eb`
Default:
=> hdf5storage additional request for INC1508572

easyconfigs/m/msgpack/msgpack-0.5.6-foss-2022b.eb, easyconfigs/p/pyfasta/pyfasta-0.5.2-foss-2022b.eb, easyconfigs/u/UMI-VarCal/UMI-VarCal-2.8.2-foss-2022b.eb
For INC1517282 - `msgpack-0.5.6-foss-2022b.eb pyfasta-0.5.2-foss-2022b.eb UMI-VarCal-2.8.2-foss-2022b.eb`
Default:
**Note:** UMI-VarCal is a rebuild
=> Fix to UMI-VarCal and additional dependencies

easyconfigs/i/InterProScan/InterProScan-5.70-102.0-foss-2023a.eb
For INC1541711 - `InterProScan-5.70-102.0-foss-2023a.eb`
Default:
=> fix(interProScan): injecting checksums

easyconfigs/p/PLINK/PLINK-2.0.0-a.5.17-gfbf-2023a.eb
plink1.90
From PR: https://github.com/easybuilders/easybuild-easyconfigs/pull/21590#issuecomment-2457403230
For INC1547323 - `PLINK-2.0.0-a.5.17-gfbf-2023a.eb`
Default:
=> fix(cascadelake): use reduced optimisation to avoid comparison failure

easyconfigs/m/MICRESS/MICRESS-7.200.eb
For INC1506374 - `MICRESS-7.200.eb`
Default:
=> MICRESS - add missing system libs to module's Bin dir

easyconfigs/n/NCCL/NCCL-2.18.3-GCCcore-12.3.0-CUDA-12.6.0.eb, easyconfigs/n/NVHPC/NVHPC-24.11-CUDA-12.6.0.eb, easyconfigs/o/OpenMPI/OpenMPI-4.1.6-NVHPC-24.11-CUDA-12.6.0.eb, easyconfigs/u/UCC-CUDA/UCC-CUDA-1.2.0-GCCcore-12.3.0-CUDA-12.6.0.eb, easyconfigs/u/UCX-CUDA/UCX-CUDA-1.14.1-GCCcore-12.3.0-CUDA-12.6.0.eb
For INC1558425
NVHPC uses a dfferent GCC base to upstream (12.3.0 instead of 13.3.0).
`OpenMPI-4.1.6-NVHPC-24.11-CUDA-12.6.0.eb`:
=> NVHPC 24.11 / CUDA 12.6.0 / OpenMPI 4.1.6

easyconfigs/b/BEAR-R-bio/BEAR-R-bio-2023a-foss-2023a-R-4.4.1.eb, easyconfigs/d/DMRcaller/DMRcaller-1.36.0-foss-2023a-R-4.4.1.eb, easyconfigs/m/methylKit/methylKit-1.30.0-foss-2023a-R-4.4.1.eb
For INC1559011 - 
- `time eb DMRcaller-1.36.0-foss-2023a-R-4.4.1.eb`
- `time eb methylKit-1.30.0-foss-2023a-R-4.4.1.eb`
and add to BEAR-r-bio
- `eb BEAR-R-bio-2023a-foss-2023a-R-4.4.1.eb --rebuild`
Default:
=> DMRcaller and methylKit for bioconductor 3.19

easyconfigs/c/CST-Studio-Suite/CST-Studio-Suite-2025.SP2-GCCcore-12.3.0-Java-17.eb
For INC1567497 - `CST-Studio-Suite-2025.SP2-GCCcore-12.3.0-Java-17.eb`
Version bump from 2024.SP2 easyconf
Default:
=> CST 2025 easyconf

easyconfigs/b/Braken/Bracken-2.9-GCCcore-12.3.0.eb, easyconfigs/k/Kraken2/Kraken2-2.1.3-gompi-2023a.eb, easyconfigs/k/Kraken2/Kraken2-2.1.3_fix_installation_for_easybuild.patch
For INC1579050 - 
`Bracken-2.9-GCCcore-12.3.0.eb`
`Kraken2-2.1.3-gompi-2023a.eb`
Default:
=> build(from-upstr): easyconfigs with version numbers edited

easyconfigs/c/code-server/code-server-4.97.2.eb
For BEAR Portal updates - `code-server-4.97.2.eb`
Default:
=> code-server 4.97.2 (version bump)

easyconfigs/d/DualSPHysics/DualSPHysics-5.2.269-foss-2023a-CUDA-12.1.1.eb, easyconfigs/d/DualSPHysics/DualSPHysics-5.2.269-foss-2023a.eb, easyconfigs/d/DualSPHysics/DualSPHysics-5.2.269_makefiles.patch
For INC1582872
N.B. developer has stopped tagging releases in GitHub so this uses the short commit hash for the download instead. See the following link for reference, linking this commit to version  `5.2.269`.
<https://github.com/DualSPHysics/DualSPHysics/commit/fc8290c703ed79a341089062d04abd2e16c82e4e#diff-49d51a651d8a7123e5101becf3d019a73155dc8dfe6b38fe20a4305eb39bfe27R39>
`DualSPHysics-5.2.269-foss-2023a.eb`
`DualSPHysics-5.2.269-foss-2023a-CUDA-12.1.1.eb`
=> DualSPHysics 5.2.269

easyconfigs/c/CST-Studio-Suite/CST-Studio-Suite-2025.SP3-GCCcore-12.3.0-Java-17.eb
For INC1589349 - `CST-Studio-Suite-2025.SP3-GCCcore-12.3.0-Java-17.eb`
Includes fix recommended by CST support to resolve the `$CST_REGSVR32` core-dump issue
Default:
=> CST 2025.SP3

easyconfigs/f/FHI-aims/FHI-aims-250320-intel-2023a.eb
For INC1592013 - `FHI-aims-250320-intel-2023a.eb`
N.B. do not install until the new direct group `p-fhi-aims` is available on BlueBEAR 
Modified post-install from previous version:
```diff
-postinstallcmds = ["cp -ar %(builddir)s/%(namelower)s.%(version)s/{CHANGELOG.md,doc,external} %(installdir)s/",
-                   "cp -ar %(builddir)s/%(namelower)s.%(version)s/{regression_tests,species_defaults} %(installdir)s/",
-                   "cp -ar %(builddir)s/%(namelower)s.%(version)s/{testcases,utilities} %(installdir)s/"]
+postinstallcmds = [
+    "cp -ar %(builddir)s/%(namelower)s.%(version)s/* %(installdir)s/",
+    "rm -rf %(installdir)s/{cmake,CMakeLists.txt,initial_cache.example.cmake,src}"
+]
```
Default:
=> Version bump and tweaks for FHI-aims-250320

easyconfigs/e/einops/einops-0.8.1-gfbf-2023a.eb, easyconfigs/f/folium/folium-0.19.5-gfbf-2023a.eb, easyconfigs/h/hatch-nodejs-version/hatch-nodejs-version-0.3.2-GCCcore-12.3.0.eb, easyconfigs/p/pystac-client/pystac-client-0.8.6-gfbf-2023a.eb, easyconfigs/s/StackSTAC/StackSTAC-0.5.1-foss-2023a.eb, easyconfigs/s/StackSTAC/StackSTAC-0.5.1_use_pdm_backend.patch, easyconfigs/t/timm/timm-1.0.8-foss-2023a.eb
For INC1590792 
1. `einops-0.8.1-gfbf-2023a.eb` -- there is an upstream einops for 2023a but this version is newer and I don't know why the upstream needs `binutils`
2. `folium-0.19.5-gfbf-2023a.eb` -- new easyconfig
3. `timm-1.0.8-foss-2023a.eb` -- upstream but in 5.0. This is modified for 4.9.4
4. `pystac-client-0.8.6-gfbf-2023a.eb` -- new easyconfig
5. `StackSTAC-0.5.1-foss-2023a.eb` -- new easyconfig. I've tried to only use the bare minimum of jupyterlab, so didn't use the jupyterbundle as I only need 2 or 3 of the components in it.
Default:
=> folium timm einops pystac_client stackstac

easyconfigs/r/rpy2/rpy2-3.5.17-foss-2023a.eb
For INC1599727 - `rpy2-3.5.17-foss-2023a.eb`
Version bump from upstream `rpy2-3.5.15-foss-2023a.eb` to match our 2023a R version (4.4.1)
Default:
=> rpy2-3.5.17 easyconf

easyconfigs/t/TreeMix/TreeMix-1.13-GCC-12.3.0.eb
For INC1603332 - `TreeMix-1.13-GCC-12.3.0.eb`
Verbatim copy from upstream: <https://github.com/easybuilders/easybuild-easyconfigs/blob/4381b95ac913e5ee4308ab683094d9a08c307553/easybuild/easyconfigs/t/TreeMix/TreeMix-1.13-GCC-12.3.0.eb>
Default:
=> TreeMix easyconf from upstream

easyconfigs/c/CellChat/CellChat-2.1.2-foss-2023a-R-4.4.1.eb
For INC1605325 - `CellChat-2.1.2-foss-2023a-R-4.4.1.eb`
- modified from upstream
- uses new repo path (pre v2 repo is archived_
- removes depedencies on `systemfonts` and `svglite`, which are provided via `R` and `R-bundle-CRAN` respectively.
Default:
=> CellChat 2.1.2 easyconf

easyconfigs/f/fumi_tools/fumi_tools-0.18.2-GCC-13.3.0.eb
For INC1614829 - `fumi_tools-0.18.2-GCC-13.3.0.eb`
Default:
**Note:** Certain fumi_tools functions require SAMtools (but not as a dependency) hence the additional install https://github.com/bear-rsg/bear-eb/issues/645
=> INC1614829 fumi_tools install

easyblocks/ansys.py, easyconfigs/a/ANSYS/ANSYS-2025R2.eb, easyconfigs/a/ANSYS_Rocky/ANSYS_Rocky-2025R2.eb
For INC1625321 - `ANSYS_Rocky-2025R2.eb`
The 9-ISO unpack requires a large amount of space in the buildpath and it's therefore necessary to move it to `/scratch` from `/dev/shm`:
```
export EASYBUILD_BUILDPATH=/scratch/${USER}/build-2024a-1
```
Default:
=> ANSYS Rocky 2025R2 (including ANSYS 2025R2)

easyconfigs/n/nanomonsv/nanomonsv-0.8.0-foss-2023a.eb
For INC1635678
Adds missing dep for nanomonsv's required binaries
```
eb nanomonsv-0.8.0-foss-2023a.eb -r --rebuild --module-only
```
Default:
=> HTSlib dep for nanomonsv
