bear-rsg/bear-eb

- easyconfigs/r/R-bundle-Bioconductor/R-bundle-Bioconductor-3.15-foss-2021b-R-4.2.0.eb
For INC1261638
N.B. special command:
```
time eb R-bundle-Bioconductor-3.15-foss-2021b-R-4.2.0.eb -r -T --skip --rebuild
```
Default:
> Add danRer11 genome to Bioconductor

- easyconfigs/q/QuPath/QuPath-0.3.2-Java-11.eb
For INC1255687- `QuPath-0.3.2-Java-11.eb` (rebuild)
Default:
> Added CHmod for binary for QuPath

- easyblocks/star_ccm.py
- easyconfigs/s/STAR-CCM+/STAR-CCM+-17.02.008.eb
For INC1263585 - `STAR-CCM+-17.02.008.eb`
Default:
> STAR-CCM+ 2022.1.1

- easyconfigs/b/BEAR-R-bio/BEAR-R-bio-2021b-foss-2021b-R-4.2.0.eb
- easyconfigs/r/RStudio-Server/RStudio-Server-1.4.1717-foss-2021b-Java-11-R-4.2.0.eb
- easyconfigs/r/RStudio-Server/Rf_countContexts.patch
For BEAR Portal - `RStudio-Server-1.4.1717-foss-2021b-Java-11-R-4.2.0.eb`
Default:
> RStudio Server for 2021b

- easyconfigs/b/betapart/betapart-1.5.6-foss-2021b-R-4.2.0.eb
For INC1261137 - `betapart-1.5.6-foss-2021b-R-4.2.0.eb`
Default:
> betapart INC1261137

- easyconfigs/g/gdm/gdm-1.5.0-3-foss-2021b-R-4.2.0.eb
For IINC1261137 - `gdm-1.5.0-3-foss-2021b-R-4.2.0.eb`
Default:
> gdm part of INC1261137

- easyconfigs/s/Salmon/Salmon-1.9.0-GCC-11.2.0.eb
- easyconfigs/s/Salmon/Salmon-1.9.0-gompi-2021b.eb
For INC1266132- `Salmon-1.9.0-gompi-2021b.eb`
An updated version of existing Salmon eb.
Default:
> INC1266132-Salmon

- easyconfigs/i/ioh/ioh-0.3.2.8.3-foss-2021b.eb
For INC1270315- `ioh-0.3.2.8.2.3-foss-2021b.eb
Default:
> new version of IOHExperimenter now known as ioh

- easyconfigs/t/TALYS/TALYS-1.96-GCCcore-11.2.0.eb
For INC1270502 - build `TALYS-1.96-GCCcore-11.2.0.eb`
Default:
> TALYS 1.96 build for 2021b

- easyconfigs/b/BEAR-R-bio/BEAR-R-bio-2021b-foss-2021b-R-4.2.0.eb
- easyconfigs/m/monocle/monocle-2.24.1-foss-2021b-R-4.2.0.eb
For INC1272027- `monocle-2.24.1-foss-2021b-R-4.2.0.eb BEAR-R_bio-2021b-R-4.2.0.eb`
Default:
> monocle install

- easyconfigs/c/cma/cma-3.2.2-foss-2021b.eb
For INC1273910 - `cma-3.2.2-foss-2021b.eb`
Default:
> cma application install

- easyconfigs/b/BEAR-R-bio/BEAR-R-bio-2021b-foss-2021b-R-4.2.0.eb
- easyconfigs/s/SpaTalk/SpaTalk-1.0-foss-2021b-R-4.2.0.eb
For INC1277494-`SpaTalk-1.0-foss-2021b-R-4.2.0.eb` `BEAR-R_bio-2021b-R-4.2.0.eb`
Default:
> INC1277494-SpaTalk

- easyconfigs/t/TOBIAS/TOBIAS-0.13.3-foss-2021b.eb
For INC1281376 - `TOBIAS-0.13.3-foss-2021b.eb`
Default:
> TOBIAS 0.13.3

- easyconfigs/d/DRAM/DRAM-1.3.6-foss-2021b.eb
- easyconfigs/s/scikit-bio/scikit-bio-0.5.7-foss-2021b.eb
- easyconfigs/t/tRNAscan-SE/tRNAscan-SE-2.0.9-GCCcore-11.2.0.eb
For INC1282321 - `DRAM-1.3.6-foss-2021b.eb`
Default:
> DRAM-1.3.6

- easyconfigs/p/PhitestR/PhitestR-0.2.0-foss-2021b-R-4.2.0.eb
For INC1283458 - `PhitestR-0.2.0-foss-2021b-R-4.2.0.eb`
Default:
> PhitestR-0.2.0

- easyconfigs/b/BEAR-R-bio/BEAR-R-bio-2021b-foss-2021b-R-4.2.0.eb
- easyconfigs/o/ottr/ottr-1.2.0-foss-2021b-R-4.2.0.eb
For INC1291774 - rebuild `BEAR-R-bio-2021b-foss-2021b-R-4.2.0.eb`
Default:
> ottr easyconf and R-bio addition

- easyconfigs/b/BIOMASS/BIOMASS-2.1.8-foss-2021b-R-4.2.0.eb
For INC1297831 - `BIOMASS-2.1.8-foss-2021b-R-4.2.0.eb`
Default:
> BIOMASS 2.1.8 easyconf

- easyconfigs/e/ecc_finder/ecc_finder-1.0.0-foss-2021b.eb
For INC1298434-`ecc_finder-1.0.0-foss-2021b.eb`
* This will be used primarily on a Ubuntu VM so please build for that, too.
* There were a few issues with the zipped/tarred v1.0.0 release so the current git master has been used
Default:
> ecc_finder

- easyconfigs/c/canopus-treemap/canopus_treemap-0.0.1-foss-2021b.eb
For INC130775 - `canopus_treemap-0.0.1-foss-2021b.eb`
Default:
> canopus app install

- easyconfigs/e/ecc_finder/ecc_finder-1.0.0-foss-2021b.eb
- easyconfigs/e/ecc_finder/ecc_finder-1.0.0_fix-paths.patch
- easyconfigs/g/Genrich/Genrich-0.6.1-GCC-11.2.0.eb
- easyconfigs/t/TideHunter/TideHunter-1.5.4-GCC-11.2.0.eb
For INC1298434
* `eb --from-pr 16407 -Tr` (to provide `Unicycler`)
* rebuild: `ecc_finder-1.0.0-foss-2021b.eb`
Default:
> Extra deps for ecc_finder and add patch to sort out paths

- easyconfigs/a/autograd/autograd-1.5-foss-2021b.eb
- easyconfigs/g/Gdspy/Gdspy-1.6.12-foss-2021b.eb
- easyconfigs/h/Harminv/Harminv-1.4.1-foss-2021b.eb
- easyconfigs/l/libGDSII/libGDSII-0.21-GCCcore-11.2.0.eb
- easyconfigs/l/libctl/libctl-4.5.1-GCCcore-11.2.0.eb
- easyconfigs/m/MPB/MPB-1.11.1-foss-2021b.eb
- easyconfigs/m/Meep/Meep-1.25.0-foss-2021b.eb
For INC1322155 - `Gdspy-1.6.12-foss-2021b.eb autograd-1.5-foss-2021b.eb libctl-4.5.1-GCCcore-11.2.0.eb Harminv-1.4.1-foss-2021b.eb MPB-1.11.1-foss-2021b.eb libGDSII-0.21-GCCcore-11.2.0.eb Meep-1.25.0-foss-2021b.eb`
Default:
**Note:** As with https://github.com/bear-rsg/easybuild-easyconfigs/pull/925 Meep must do `ssh $HOSTNAME` on build node before building
> Meep install for INC1322155

- easyconfigs/o/OpenFOAM/OpenFOAM-v2206-foss-2021b.eb
For INC1327792 - `OpenFOAM-v2206-foss-2021b.eb`
Default:
> OpenFOAM 2206

- easyconfigs/c/CASTEP/CASTEP-22.11-foss-2021b.eb
- easyconfigs/c/CASTEP/CASTEP-22.11_flexiblas.patch
For INC1309332 - `CASTEP-22.11-foss-2021b.eb`
Default:
> CASTEP 22.11

- easyconfigs/j/jellyfish/Jellyfish-2.3.0-GCC-11.2.0.eb
For INC1333673 - `Jellyfish-2.3.0-GCC-11.2.0.eb`
Default:
> Jellyfish app install based on upstream

- easyconfigs/g/Grace/Grace-5.1.25-5build1.patch
- easyconfigs/g/Grace/Grace-5.1.25-foss-2021b-5build1.eb
- easyconfigs/g/Grace/Grace-5.1.25-tirpc-dependency.patch
For INC1333098 - `Grace-5.1.25-foss-2021b-5build1.eb`
**Live Build Notes**
- I've left the runtests step in -- but if building with X forwarded (needed to run the tests), the graphs will pop up and will need manually closing before it proceeds to generate the next .agr in examples. I'd advise not building with X forwarded
- Both patches needed: `build1` patch to handle the type1 font rendering; `libtirpc` patch so `grconvert` builds
Default:
> Grace 5.1.25 

- easyconfigs/c/CRYSTAL/CRYSTAL-23-iomkl-2021b.eb
For INC1309920 - `CRYSTAL-23-iomkl-2021b.eb --rebuild`
Default:
> Restrict CRYSTAL23 permissions

- easyconfigs/g/GeoMxNGSPipeline/GeoMxNGSPipeline-2.3.3.10.eb
For INC1335311 - `GeoMxNGSPipeline-2.3.3.10.eb`
Default:
> GeoMxNGSPipeline

- easyconfigs/i/icellnet/icellnet-1.0-foss-2021b-R-4.2.0.eb
For INC1334997 - `icellnet-1.0-foss-2021b-R-4.2.0.eb`
Default:
> icellnet app install

- easyconfigs/b/BAT/BAT-2.9.2-foss-2021b-R-4.2.0.eb
- easyconfigs/h/hypvervolume/hypervolume-3.1.0-foss-2021b-R-4.2.0.eb
- easyconfigs/s/sars/sars-1.3.6-foss-2021b-R-4.2.0.eb
For INC1336751 - multiple easyconfigs
`hypervolume-3.1.0-foss-2021b-R-4.2.0.eb`
`BAT-2.9.2-foss-2021b-R-4.2.0.eb`
`sars-1.3.6-foss-2021b-R-4.2.0.eb`
**Notes**
BAT has a hypervolume dependency so install after hypervolume
Default:
> hypervolume, BAT, and sars

- easyconfigs/b/BEAR-R-bio/BEAR-R-bio-2021b-foss-2021b-R-4.2.0.eb
- easyconfigs/c/cyCombine/cyCombine-0.2.15-foss-2021b-R-4.2.0.eb
For INC1335015 - `cyCombine-0.2.15-foss-2021b-R-4.2.0.eb`
Default:
> cyCombine app install

- easyconfigs/a/astropy/astropy-5.0.4-foss-2021b.eb
- easyconfigs/e/emcee/emcee-3.1.3-foss-2021b.eb
- easyconfigs/l/lightkurve/lightkurve-2.3.0-foss.2021b.eb
For INC1338768 - `lightkurve-2.3.0-foss.2021b.eb`
Also build: `emcee-3.1.3-foss-2021b.eb`
Default:
> lightkurve and emcee

- easyconfigs/h/HDBSCAN/HDBSCAN-0.8.29-foss-2021b.eb
- easyconfigs/p/pbjam/pbjam-1.0.0-foss-2021b.eb
For INC1338768 - `pbjam-1.0.0-foss-2021b.eb`
Default:
> pbjam and deps

- easyconfigs/i/IGV/IGV-2.16.0-Java-11.eb
For INC1341875 - `IGV-2.16.0-Java-11.eb`
Default:
> IGV 2.16.0

- easyconfigs/v/VASP/VASP-6.3.2-foss-2022a.eb
- easyconfigs/v/VASP/enableHDF5-gnu.patch
For INC1322165 - `VASP-6.3.2-foss-2022a.eb`
N.B. the access group `p-vasp6` has already been created in BEAR Admin
Default:
> VASP 6.3.2

- easyconfigs/h/HTSlib/HTSlib-1.16-GCC-11.3.0.eb
- easyconfigs/m/modbam2bed/modbam2bed-0.7.0-GCC-11.3.0.eb
For INC1338954 - `modbam2bed-0.7.0-GCC-11.3.0.eb`
Default:
> modbam2bed in 2022a

- easyconfigs/f/FastME/FastME-2.1.6.4-GCC-11.2.0.eb
- easyconfigs/m/MCL/MCL-14.137-GCCcore-11.2.0.eb
- easyconfigs/m/MCL/MCL-14.137_fixperl.patch
- easyconfigs/o/OrthoFinder/OrthoFinder-2.5.4-foss-2021b.eb
For INC1340365 - `FastME-2.1.6.4-GCC-11.2.0.eb MCL-14.137-GCCcore-11.2.0.eb OrthoFinder/OrthoFinder-2.5.4-foss-2021b.eb`
Default:
> OrthoFinder app installation

- easyconfigs/s/Stata/Stata-17.rev2023-01-10.eb
For INC1347925 - `Stata-17.rev2023-01-10.eb`
Build in 2022a
This easyconf is a mix of our previous Stata conf and the Stata17 available from upstream.
Default:
> Stata 17 rev 2023-01-10

- easyconfigs/p/poetry/poetry-1.2.2-GCCcore-11.3.0.eb
- easyconfigs/p/poetry/poetry-1.2.2-foss-2022a.eb
- easyconfigs/p/pytesseract/pytesseract-0.3.10-foss-2022a.eb
- easyconfigs/s/SHAP/SHAP-0.41.0-foss-2022a.eb
For 	INC1348739 - `pytesseract-0.3.10-foss-2022a.eb`
And rebuild `SHAP-0.41.0-foss-2022a.eb`
Default:
> pytesseract easyconf

- easyconfigs/e/embarcadero/embarcadero-1.2.0.1003-foss-2021b-R-4.2.0.eb
- easyconfigs/f/fuzzySim/fuzzySim-4.9.2-foss-2021b-R-4.2.0.eb
For INC1350790 - `embarcadero-1.2.0.1003-foss-2021b-R-4.2.0.eb fuzzySim-4.9.2-foss-2021b-R-4.2.0.eb`
Default:
> embarcadero and fuzzySim

- easyconfigs/v/VASP/VASP-6.3.2-foss-2022a-Wannier90.eb
- easyconfigs/v/VASP/enableHDF5-Wannier90.patch
- easyconfigs/w/Wannier90/Wannier90-3.1.0-foss-2022a-serial.eb
For INC1322165 - `VASP-6.3.2-foss-2022a-Wannier90.eb`
Default:
> VASP 6.3.2 with Wannier90

- easyconfigs/v/VASP/VASP-6.3.2-intel-2022a.eb
- easyconfigs/v/VASP/VASP-6.3.2-nvofbf-2022.07.eb
For INC1348157
`VASP-6.3.2-intel-2022a.eb`:
`VASP-6.3.2-nvofbf-2022.07.eb`:
> VASP intel and nvofbf

- easyconfigs/c/cell2location/cell2location-0.1.3-foss-2022a.eb
- easyconfigs/p/PyTorch-Lightning/PyTorch-Lightning-1.9.3-foss-2022a.eb
- easyconfigs/p/poetry/poetry-1.2.2-GCCcore-11.3.0.eb
- easyconfigs/s/scvi-tools/scvi-tools-0.20.1-foss-2022a.eb
For INC1350880
Rebuild:
Upstream builds:
`cell2location-0.1.3-foss-2022a.eb`:
> cell2location (CPU)

- easyconfigs/c/cell2location/cell2location-0.1.3-foss-2022a-CUDA-11.7.0.eb
- easyconfigs/p/PyTorch-Lightning/PyTorch-Lightning-1.9.3-foss-2022a-CUDA-11.7.0.eb
- easyconfigs/s/scvi-tools/scvi-tools-0.20.1-foss-2022a-CUDA-11.7.0.eb
For INC1350880
`cell2location-0.1.3-foss-2022a-CUDA-11.7.0.eb`:
> cell2location (GPU)

- easyconfigs/a/ANSYS/ANSYS-2023R1.eb
For INC1349160 - `ANSYS-2023R1.eb`
Default:
> ANSYS 2023r1

- .flake8
- easyconfigs/a/ANSYS/ANSYS-2023R1.eb
- easyconfigs/a/astropy/astropy-5.0.4-foss-2021b.eb
- easyconfigs/b/BIOMASS/BIOMASS-2.1.8-foss-2021b-R-4.2.0.eb
- easyconfigs/b/Bisbee/Bisbee-20210108-foss-2021b-R-4.2.0.eb
- easyconfigs/b/betapart/betapart-1.5.6-foss-2021b-R-4.2.0.eb
- easyconfigs/c/CASTEP/CASTEP-22.11-foss-2021b.eb
- easyconfigs/c/CellChat/CellChat-1.6.0-foss-2021b-R-4.2.0.eb
- easyconfigs/c/ChimeraX/ChimeraX-1.5-linux-x86_64.eb
- easyconfigs/c/canopus-treemap/canopus_treemap-0.0.1-foss-2021b.eb
- easyconfigs/c/cma/cma-3.2.2-foss-2021b.eb
- easyconfigs/d/DCC/DCC-0.5.0-foss-2021b.eb
- easyconfigs/d/DRAM/DRAM-1.3.6-foss-2021b.eb
- easyconfigs/e/embarcadero/embarcadero-1.2.0.1003-foss-2021b-R-4.2.0.eb
- easyconfigs/g/Grace/Grace-5.1.25-foss-2021b-5build1.eb
- easyconfigs/g/Groovy/Groovy-4.0.3-Java-11.eb
- easyconfigs/i/icellnet/icellnet-1.0-foss-2021b-R-4.2.0.eb
- easyconfigs/i/ioh/ioh-0.3.2.8.3-foss-2021b.eb
- easyconfigs/j/Jellyfish/Jellyfish-2.3.0-GCC-11.2.0.eb
- easyconfigs/j/jax/jax-0.3.13-foss-2021b-CUDA-11.4.1.eb
- easyconfigs/l/libctl/libctl-4.5.1-GCCcore-11.2.0.eb
- easyconfigs/m/Micro-Manager/Micro-Manager-1.4.24-foss-2021b.eb
- easyconfigs/m/modbam2bed/modbam2bed-0.7.0-GCC-11.2.0.eb
- easyconfigs/m/modbam2bed/modbam2bed-0.7.0-GCC-11.3.0.eb
- easyconfigs/p/pcgr/pcgr-1.0.3.eb
- easyconfigs/p/pcgr/pcgr-1.2.0.eb
- easyconfigs/p/pcgrr/pcgrr-1.0.3.eb
- easyconfigs/p/pcgrr/pcgrr-1.2.0.eb
- easyconfigs/q/QuPath/QuPath-0.3.2-Java-11.eb
- easyconfigs/s/SpaTalk/SpaTalk-1.0-foss-2021b-R-4.2.0.eb
Modified to run some basic checks on indentation, line-length etc.
> Change flake8 config to check *.eb files too

- .flake8
- easyconfigs/b/Barracuda_Virtual_Reactor/Barracuda_Virtual_Reactor-22.1.1-GCCcore-11.3.0.eb
For INC1346010 - `Barracuda_Virtual_Reactor-22.1.1-GCCcore-11.3.0.eb`
Default:
> Barracuda_Virtual_Reactor v22

- easyconfigs/b/BEAR-R-bio/BEAR-R-bio-2021b-foss-2021b-R-4.2.0.eb
- easyconfigs/f/faahKO/faahKO-1.36.0-foss-2021b-R-4.2.0.eb
- easyconfigs/i/iRF/iRF-3.0.0-foss-2021b-R-4.2.0.eb
- easyconfigs/p/pandaR/pandaR-1.28.0-foss-2021b-R-4.2.0.eb
For INC1353755 and INC1353452
`faahKO-1.36.0-foss-2021b-R-4.2.0.eb iRF-3.0.0-foss-2021b-R-4.2.0.eb pandaR-1.28.0-foss-2021b-R-4.2.0.eb`:
Rebuild: `msPurity-1.22.0-foss-2021b-R-4.2.0.eb`
Rebuild: `BEAR-R-bio-2021b-foss-2021b-R-4.2.0.eb`
> more for MSc

- easyconfigs/i/iRF/iRF-3.0.0-foss-2021b-R-4.2.0.eb
For INC1353755 - Rebuild: `iRF-3.0.0-foss-2021b-R-4.2.0.eb`
Default:
> R_LIBS_SITE

- easyconfigs/p/pydot/pydot-1.4.2-GCCcore-11.2.0.eb
For INC1348517 - `pydot-1.4.2-GCCcore-11.2.0.eb`
Default:
> pydot as part of NSBAS install

- easyconfigs/m/MNE-Python/MNE-Python-1.3.1-foss-2022a.eb
For INC1353996 - `MNE-Python-1.3.1-foss-2022a.eb`
Default:
> MNE-Python 1.3.1

- easyconfigs/s/STAR-CCM+/STAR-CCM+-18.02.008.eb
For INC1354525 - `STAR-CCM+-18.02.008.eb`
Default:
> STAR-CCM+ 18 easyconf

- easyconfigs/b/BEAR-Python-MSc-Bioinformatics/BEAR-Python-MSc-Bioinformatics-2021b-foss-2021b.eb
For INC1360506
Rebuild `BEAR-Python-MSc-Bioinformatics-2021b-foss-2021b.eb`:
> add scikit-image

- easyconfigs/i/InterProScan/InterProScan-5.61-93.0-foss-2022a.eb
For INC1357699 - `InterProScan-5.61-93.0-foss-2022a.eb`
Default:
> InterProScan

- easyconfigs/p/pharokka/pharokka-1.2.0.eb
For INC1358682 - `pharokka-1.2.0.eb`
Default:
> pharokka app install

- easyconfigs/b/BEAR-R-bio/BEAR-R-bio-2021b-MSc-foss-2021b-R-4.2.0.eb
- easyconfigs/r/R-bundle-Bioconductor/R-bundle-Bioconductor-3.16-foss-2021b-R-4.2.0.eb
For INC1357833
`BEAR-R-bio-2021b-MSc-foss-2021b-R-4.2.0.eb`:
> New Bioconductor for MSc

- easyconfigs/b/BEAR-Python-MSc-Bioinformatics/BEAR-Python-MSc-Bioinformatics-2021b-foss-2021b.eb
- easyconfigs/r/R-bundle-Bioconductor/R-bundle-Bioconductor-3.16-foss-2021b-R-4.2.0.eb
- easyconfigs/s/sequenza-utils/sequenza-utils-3.0.0-foss-2021b-MSc.eb
- easyconfigs/s/sequenza/sequenza-3.0.0-foss-2021b-MSc.eb
Bioconductor was built in #149 with the change here.
build `sequenza-utils-3.0.0-foss-2021b-MSc.eb sequenza-3.0.0-foss-2021b-MSc.eb`:
rebuild `BEAR-Python-MSc-Bioinformatics-2021b-foss-2021b.eb`:
> missing deps

- easyconfigs/c/cma/cma-3.3.0-foss-2022a.eb
- easyconfigs/c/coexist/coexist-0.3.1-foss-2022a.eb
- easyconfigs/n/natsort/natsort-8.2.0-foss-2022a.eb
- easyconfigs/p/PICI-LIGGGHTS/PICI-LIGGGHTS-3.8.1-foss-2022a.eb
- easyconfigs/p/pyvista/pyvista-0.36.1-foss-2022a.eb
For INC1358257 - `PICI-LIGGGHTS-3.8.1-foss-2022a.eb coexist-0.3.1-foss-2022a.eb natsort-8.2.0-foss-2022a.eb pyvista-0.36.1-foss-2022a.eb`
Default:
> INC1358257 - various

- easyconfigs/a/AlphaFold/AlphaFold-2.3.1-foss-2022a-CUDA-11.7.0.eb
- easyconfigs/a/AlphaFold/AlphaFold-2.3.1-foss-2022a.eb
- easyconfigs/a/AlphaFold/AlphaFold-2.3.1_use_openmm_7.7.0.patch
- easyconfigs/h/HH-suite/HH-suite-3.3.0-gompi-2022a.eb
- easyconfigs/k/Kalign/Kalign-3.3.5-GCCcore-11.3.0.eb
For INC1361772
This is broadly copied from https://github.com/easybuilders/easybuild-easyconfigs/pull/17604, with the only key difference being that it uses OpenMM 7.7.0, which is already available in upstream.
N.B. ideally we'll want to rebuild at some point with a CUDA-enabled OpenMM but there are currently compiler-related issues.
`AlphaFold-2.3.1-foss-2022a.eb`:
`AlphaFold-2.3.1-foss-2022a-CUDA-11.7.0.eb`:
> Alphafold and deps

- easyconfigs/n/nanopolish/nanopolish-0.14.0-foss-2021b.eb
- easyconfigs/v/VBZ-Compression/VBZ-Compression-1.0.2-gompi-2021b.eb
For INC1362543 - `VBZ-Compression-1.0.2-gompi-2021b.eb nanopolish-0.14.0-foss-2021b.eb`
Default:
> nanopolish install

- easyconfigs/b/BEAR-R-bio/BEAR-R-bio-2021b-MSc-foss-2021b-R-4.2.0.eb
- easyconfigs/m/MOFA2/MOFA2-1.8.0-foss-2021b-R-4.2.0.eb
- easyconfigs/s/smotefamily/smotefamily-1.3.1-foss-2021b-R-4.2.0.eb
For INC1357833
`MOFA2-1.8.0-foss-2021b-R-4.2.0.eb smotefamily-1.3.1-foss-2021b-R-4.2.0.eb`:
rebuild `BEAR-R-bio-2021b-MSc-foss-2021b-R-4.2.0.eb`:
> MOFA2 and smotefamily

- easyconfigs/i/ilastik/ilastik-1.4.0-linux-x64.eb
For INC1365303 - `ilastik-1.4.0-linux-x64.eb`
For 2022a.
Default:
> ilastik-1.4.0

- easyconfigs/s/SSAM/SSAM-1.0.2-foss-2021b.eb
- easyconfigs/s/SSAM/SSAM-1.0.2-use_arrow_for_data_exchange.patch
For INC1342020 - `SSAM-1.0.2-foss-2021b.eb`
Associated patch - `SSAM-1.0.2-use_arrow_for_data_exchange.patch`
Default:
> Add arrow-R dep and patch

- easyconfigs/m/mne-rsa/mne-rsa-0.8-foss-2022a.eb
For INC1371233 - `mne-rsa-0.8-foss-2022a.eb`
Default:
> mne-rsa app build

- easyconfigs/l/LiBiNorm/LiBiNorm-2.5.eb
For INC1371009 - `LiBiNorm-2.5.eb`
Default:
VM lunadiee-epi-virtualmchine
> LiBiNorm executable

- easyconfigs/p/ptwt/ptwt-0.1.4.post2-foss-2022a-CUDA-11.7.0.eb
- easyconfigs/p/ptwt/ptwt-0.1.4.post2-foss-2022a.eb
- easyconfigs/s/sklearn-pandas/sklearn-pandas-2.2.0-foss-2022a.eb
For INC1371895
`wandb-0.13.6-GCC-11.3.0.eb`
`ptwt-0.1.4.post2-foss-2022a.eb sklearn-pandas-2.2.0-foss-2022a.eb`:
`ptwt-0.1.4.post2-foss-2022a-CUDA-11.7.0.eb`:
> ptwt and friends

- easyconfigs/t/Transformers/Transformers-4.29.2-foss-2022a-CUDA-11.7.0.eb
- easyconfigs/t/Transformers/Transformers-4.29.2-foss-2022a.eb
For INC1375854
`Transformers-4.29.2-foss-2022a.eb`:
`Transformers-4.29.2-foss-2022a-CUDA-11.7.0.eb`:
> Transformers

- easyconfigs/h/Horovod/Horovod-0.28.0-foss-2022a-CUDA-11.7.0-PyTorch-2.0.1.eb
- easyconfigs/p/PyTorch-Lightning/PyTorch-Lightning-2.0.2-foss-2022a-CUDA-11.7.0.eb
- easyconfigs/p/PyTorch/PyTorch-2.0.1-foss-2022a-CUDA-11.7.0.eb
- easyconfigs/t/torchvision/torchvision-0.15.2-foss-2022a-CUDA-11.7.0.eb
For INC1369832 - deliberatly going with the provided wheels for PyTorch
`Horovod-0.28.0-foss-2022a-CUDA-11.7.0-PyTorch-2.0.1.eb PyTorch-Lightning-2.0.2-foss-2022a-CUDA-11.7.0.eb torchvision-0.15.2-foss-2022a-CUDA-11.7.0.eb`:
> PyTorch (and friends)

- easyconfigs/p/pyseer/pyseer-1.3.11-foss-2022a.eb
For INC1381450 - `pyseer-1.3.11-foss-2022a.eb`
Default:
> pyseer easyconf

- easyconfigs/m/MICRESS/MICRESS-7.200.eb
For INC1384896 - `MICRESS-7.200.eb`
System install - build against 2022a
Default:
> MICRESS 7.2

- easyconfigs/r/RootPainter/RootPainter-0.2.27.0-foss-2022a-CUDA-11.7.0.eb
- easyconfigs/r/RootPainter/python-deps.patch
For INC1377635 - `RootPainter-0.2.27.0-foss-2022a-CUDA-11.7.0.eb`
Default:
> RootPainter

- easyconfigs/c/cddlib/cddlib-0.94m-GCCcore-11.3.0.eb
- easyconfigs/g/gap/gap-4.12.2-foss-2022a.eb
- easyconfigs/g/gap/gap-4.12.2_cddlib.patch
- easyconfigs/l/lrslib/lrslib-7.2-gompi-2022a.eb
- easyconfigs/l/lrslib/lrslib-7.2_use-EB-values.patch
- easyconfigs/s/Singular/Singular-4.3.2-gfbf-2022a.eb
For INC1387220 - `gap-4.12.2-foss-2022a.eb`
Default:
> gap and deps

- easyconfigs/x/Xerces-C++/Xerces-C++-3.2.3-GCCcore-11.3.0.eb
For INC1383181 - `Xerces-C++-3.2.3-GCCcore-11.3.0.eb`
Default:
> Xerces-C++ (Pdal dep)

- easyconfigs/b/BEAR-R-bio/BEAR-R-bio-2022a-foss-2022a-R-4.2.3.eb
- easyconfigs/i/IRkernel/IRkernel-1.3.2-foss-2022a-R-4.2.3.eb
For portal
`BEAR-R-bio-2022a-foss-2022a-R-4.2.3.eb IRkernel-1.3.2-foss-2022a-R-4.2.3.eb`:
> Portal related modules

- easyconfigs/p/pyvis/pyvis-0.2.1-foss-2021b.eb
For INC1390919 - `pyvis-0.2.1-foss-2021b.eb`
Default:
> pyvis app install

- easyblocks/rosetta.py
- easyconfigs/r/Rosetta/Rosetta-3.13-foss-2022a.eb
- easyconfigs/r/Rosetta/Rosetta-3.13_remove-libxml2.patch
- easyconfigs/r/Rosetta/Rosetta_compiler_fix.patch
For INC1391868- `Rosetta-3.13-foss-2022a.eb`
Default:
> Rosetta app install

- easyconfigs/f/fundiversity/fundiversity-1.1.1-foss-2022a-R-4.2.3.eb
For INC1399759 - `fundiversity-1.1.1-foss-2022a-R-4.2.3.eb`
Default:
> fundiversity-1.1.1 for INC1399759

- easyconfigs/w/windspharm/windspharm-1.7.0-foss-2022a.eb
- easyconfigs/w/windspharm/windspharm-1.7.0_numpy-compat.patch
For INC1402171 - `windspharm-1.7.0-foss-2022a.eb`
Default:
> windspharm

- easyconfigs/b/baysor/baysor-0.6.2-linux-x86_64.eb
For  INC1404401 - `baysor-0.6.2-linux-x86_64.eb`
Default:
> Baysor v0.6.2

- easyconfigs/l/lollipops/lollipops-1.6.0.eb
For INC1412150 - `lollipops-1.6.0.eb`
Build env 2022a 
Default:
> lollipops 1.6.0

- easyconfigs/g/Groovy/Groovy-4.0.15-Java-17.eb
- easyconfigs/q/QuPath/QuPath-0.4.4-Java-17.eb
For INC1423500 - `QuPath-0.4.4-Java-17.eb` (in 2022b for `Java/17`)
Default:
> QuPath 0.4.4

- easyconfigs/p/prokka/prokka-1.14.5-gompi-2021b.eb
For INC1422338
Repeat https://github.com/bear-rsg/easybuild-easyconfigs/pull/878 for 2021b version.
rebuild: `prokka-1.14.5-gompi-2021b.eb`:
> Fix tbl2asn in prokka

- easyblocks/cp2k.py
- easyconfigs/c/CP2K/CP2K-2023.1-foss-2021b-CUDA-11.4.1.eb
- easyconfigs/c/CP2K/CP2K-2023.1-foss-2021b.eb
- easyconfigs/c/CP2K/CP2K-2023.1_smoketest.patch
- easyconfigs/c/CP2K/CP2K-2023.2-foss-2022a-CUDA-11.7.0.eb
- easyconfigs/c/CP2K/CP2K-2023.2-foss-2022a.eb
For INC1426322
easyblock changes are from upstream PRs
rebuild `CP2K-2023.1-foss-2021b-CUDA-11.4.1.eb`:
`CP2K-2023.2-foss-2022a.eb`:
`CP2K-2023.2-foss-2022a-CUDA-11.7.0.eb`
> CUDA CP2K fix

- easyconfigs/v/VASP/VASP-6.4.2-foss-2022a-Wannier90.eb
- easyconfigs/v/VASP/VASP-6.4.2-foss-2022a.eb
- easyconfigs/v/VASP/VASP-6.4.2-intel-2022a.eb
For INC1429034
`VASP-6.4.2-intel-2022a.eb VASP-6.4.2-foss-2022a-Wannier90.eb VASP-6.4.2-foss-2022a.eb`:
> VASP 6.4.2

- easyconfigs/b/BiobankRead-Bash/BiobankRead-Bash-3.1.1-20190507-foss-2022a.eb
For INC1422386 - `BiobankRead-Bash-3.1.1-20190507-foss-2022a.eb`
Default:
> BiobankRead-Bash

- easyconfigs/e/epiAneufinder/epiAneufinder-1.0.1-foss-2021b-R-4.2.0.eb
For INC1426176 - `epiAneufinder-1.0.1-foss-2021b-R-4.2.0.eb`
Default:
> Add epiAneufinder easyconf

- easyconfigs/a/adehabitatHR/adehabitatHR-0.4.21-foss-2021b-R-4.2.0.eb
- easyconfigs/a/ads/ads-1.5-9-foss-2021b-R-4.2.0.eb
- easyconfigs/f/fauxcurrence/fauxcurrence-1.2.0-foss-2021b-R-4.2.0.eb
For:
INC1427818 - `fauxcurrence-1.2.0-foss-2021b-R-4.2.0.eb`
INC1427881 - `adehabitatHR-0.4.21-foss-2021b-R-4.2.0.eb`
INC1427852 - `ads-1.5-9-foss-2021b-R-4.2.0.eb`
Default:
> R packages: adehabitatHR, ads, fauxcurrence

- easyconfigs/b/Bowtie/Bowtie-1.3.1-GCC-12.2.0.eb
- easyconfigs/s/ShortStack/ShortStack-4.0.2-foss-2022b.eb
- easyconfigs/s/ShortTracks/ShortTracks-1.1-foss-2022b.eb
- easyconfigs/s/strucVis/strucVis-0.7-foss-2022b.eb
- easyconfigs/t/tbb/tbb-2021.10.0-GCCcore-12.2.0.eb
- easyconfigs/t/tbb/tbb-2021.10.0_null-address.patch
- easyconfigs/v/ViennaRNA/ViennaRNA-2.6.4-foss-2022b.eb
For INC1427527 - `ShortStack-4.0.2-foss-2022b.eb`
Default:
> ShortStack

- easyconfigs/d/dcm2bids/dcm2bids-3.1.1-foss-2022a.eb
- easyconfigs/d/dcm2bids/dcm2bids-3.1.1-foss-2022b.eb
For INC1429188 - `dcm2bids-3.1.1-foss-2022a.eb`
Default:
> dcm2bids easyconf

- easyconfigs/d/deal.II/deal.II-9.5.1-foss-2022b-muparser.eb
- easyconfigs/l/Lethe/Lethe-20230901-foss-2022b.eb
- easyconfigs/l/Lethe/Lethe-20231028-foss-2022b.eb
For INC1432823
`Lethe-20230901-foss-2022b.eb`:
> deal.II/Lethe with muParser

- easyconfigs/m/Mesquite/Mesquite-2.3.0-GCCcore-11.3.0.eb
- easyconfigs/o/OpenFOAM-Extend/OpenFOAM-Extend-5.0-20230821-foss-2022a.eb
- easyconfigs/p/ParMGridGen/ParMGridGen-1.0-gompi-2022a.eb
For INC1433733 - `OpenFOAM-Extend-5.0-20230821-foss-2022a.eb`
Default:
> OpenFOAM-Extend 5.0

- easyconfigs/n/numbakit-ode/numbakit-ode-0.5-foss-2022a.eb
For INC1436330 - `numbakit-ode-0.5-foss-2022a.eb`
Default:
> numbakit-ode app install

- easyconfigs/b/Bismark/Bismark-0.24.2-foss-2021b.eb
For INC1441948 - `Bismark-0.24.2-foss-2021b.eb`
Default:
> bismark 0.24.2

- easyconfigs/p/picard/picard-2.27.5-Java-11.0.18.eb
- easyconfigs/p/picard/picard-2.27.5-Java-11.eb
For INC1442486 - `picard-2.27.5-Java-11.eb` 
Default:
Java version required for it to be loaded with R/4.3.1
As it needs to be built in **2022b** env
> picard for INC1442486

- easyconfigs/l/libleidenalg/libleidenalg-0.11.1-foss-2022a.eb
For INC1437159  - `libleidenalg-0.11.1-foss-2022a.eb`
Default:
> libleidenalg for scenicplus

- easyconfigs/d/DeepLabCut/DeepLabCut-2.3.6-foss-2022a-CUDA-11.7.0.eb
- easyconfigs/d/DeepLabCut/DeepLabCut-2.3.6-foss-2022a.eb
For INC1442690 - `DeepLabCut-2.3.6-foss-2022a-CUDA-11.7.0.eb DeepLabCut-2.3.6-foss-2022a.eb`
Default:
GPU version
> DeepLabCut app install for INC1442690

- easyconfigs/o/OpenMDAO/OpenMDAO-3.29.0-foss-2022a.eb
- easyconfigs/p/pyCycle/pyCycle-4.2.1-foss-2022a.eb
For INC1443235 - `OpenMDAO-3.29.0-foss-2022a.eb`
For INC1443240 - `pyCycle-4.2.1-foss-2022a.eb`
Default:
> OpenMDAO and pyCycle

- easyconfigs/p/pyperlin/pyperlin-1.1.0-foss-2022a-CUDA-11.7.0.eb
For INC1444611 - `pyperlin-1.1.0-foss-2022a-CUDA-11.7.0.eb`
Default:
**Note:** GPU build only
sanity test done using usage example found [here](https://pypi.org/project/pyperlin/)
> pyperlin for INC1444611

- easyconfigs/c/CGmapTools/CGmapTools-0.1.2-GCC-11.3.0.eb
- easyconfigs/c/CGmapTools/CGmapTools-0.1.2_add-Makefile.patch
- easyconfigs/s/SAMtools/SAMtools-0.1.20-GCC-11.3.0.eb
- easyconfigs/s/SAMtools/SAMtools-0.1.20_Makefile-ncurses.patch
For INC1447688 - `CGmapTools-0.1.2-GCC-11.3.0.eb`
Default:
> CGmapTools 0.1.2

- easyconfigs/q/quarto-cli/quarto-cli-1.4.533.eb
For INC1450692 - `quarto-cli-1.4.533.eb`
Default:
> quarto-cli app build for INC1450692

- easyconfigs/m/MAnorm2_utils/MAnorm2_utils-1.0.0-2021b.eb
For INC1451688 - `MAnorm2_utils-1.0.0-2021b.eb`
Default:
> MAnorm2 app build for INC1451688

- easyconfigs/g/Groovy/Groovy-4.0.17-Java-17.eb
- easyconfigs/q/QuPath/QuPath-0.5.0-Java-17.eb
For INC1453951 - `QuPath-0.5.0-Java-17.eb`
Default:
> QuPath 0.5.0 &  Groovy

- easyconfigs/g/GULP/GULP-6.2-foss-2022a.eb
- easyconfigs/g/GULP/GULP-6.2_fftw-mpi-blas-linking-gcc.patch
For INC1452005 - `GULP-6.2-foss-2022a.eb`
Default:
> GULP install for INC1452005

- easyconfigs/o/OpenFOAM/OpenFOAM-v2212-wmake-OpenMPI.patch
- easyconfigs/o/OpenFOAM/OpenFOAM-v2312-cleanup.patch
- easyconfigs/o/OpenFOAM/OpenFOAM-v2312-foss-2022b.eb
For INC1455696
`OpenFOAM-v2312-foss-2022b.eb` (based on a upstream PR for this in `2023a`):
> OpenFOAM v2312

- easyconfigs/o/OpenPose/OpenPose-1.7.0-foss-2022a-CUDA-11.7.0.eb
- easyconfigs/o/OpenPose/OpenPose-1.7.0_fix.patch
For INC1394147 - `OpenPose-1.7.0-foss-2022a-CUDA-11.7.0.eb`
Default:
**Note:** this is a GPU build only
> OpenPose app install

- easyconfigs/b/BUSCO/BUSCO-5.4.7-foss-2022b.eb
For INC1457124 - `BUSCO-5.4.7-foss-2022b.eb`
Default:
> BUSCO for INC1457124

- easyconfigs/a/ABRicate/ABRicate-1.0.0-gompi-2022a.eb
- easyconfigs/a/any2fasta/any2fasta-0.4.2-GCCcore-11.3.0.eb
For INC1456868 - `any2fasta-0.4.2-GCCcore-11.3.0.eb ABRicate-1.0.0-gompi-2022a.eb`
Default:
> ABRicate for INC1456868

- easyconfigs/c/COMSOL/COMSOL-6.1.0.357.eb
For INC1455332 - `COMSOL-6.1.0.357.eb`
This is a version-drop of upstream's COMSOL 6.2.
Default:
> COMSOL 6.1 easyconf

- easyconfigs/a/ANSYS/ANSYS-2024R1.eb
For INC1463224 - `ANSYS-2024R1.eb`
Default:
Note: _DesignModeler_ still appears to not work with this version.
> ANSYS 2024R1 easyconf

- easyconfigs/a/ABAQUS/ABAQUS-2024-hotfix-2405.eb
For INC1464609 - `ABAQUS-2024-hotfix-2405.eb`
Version bump from upstream.
Default:
> Abaqus 2024 hotfix 2405

- easyconfigs/s/steinbock/steinbock-0.16.1-foss-2022a.eb
- easyconfigs/s/steinbock/steinbock-0.16.1_deps.patch
For INC1456505 - `steinbock-0.16.1-foss-2022a.eb`
Default:
> steinbock for INC1456505

- easyconfigs/c/Cython/Cython-0.29.37-GCCcore-12.2.0.eb
- easyconfigs/m/MNE-Python/MNE-Python-1.6.1-foss-2022b.eb
- easyconfigs/m/Meson/Meson-1.1.1-GCCcore-12.2.0.eb
- easyconfigs/m/meson-python/meson-python-0.13.2-GCCcore-12.3.0.eb
- easyconfigs/n/NiBabel/NiBabel-5.2.0-gfbf-2022b.eb
- easyconfigs/n/Nilearn/Nilearn-0.10.3-gfbf-2022b.eb
- easyconfigs/o/OpenMEEG/OpenMEEG-2.5.7-foss-2022b.eb
- easyconfigs/o/OpenMEEG/OpenMEEG-2.5.7_find-blas-lapack-from-cmake.patch
- easyconfigs/pydicom/pydicom-2.4.4-GCCcore-12.2.0.eb
For INC1469741 - these are all taken from 2023a upstream and changed to 2022b.
Default:
> MNE (and deps)

- easyconfigs/b/BuDDy/BuDDy-2.4-GCCcore-12.2.0.eb
- easyconfigs/m/Maude/Maude-3.1-GCCcore-12.2.0.eb
- easyconfigs/t/Tamarin_prover/Tamarin_prover-1.8.0-GCCcore-12.2.0.eb
> Tamarin_prover and deps

- easyconfigs/m/MNE-Python/MNE-Python-1.6.1-foss-2022b.eb
> add mne-bids

- easyconfigs/a/alsa-lib/alsa-lib-1.2.10.eb
- easyconfigs/m/MATLAB/MATLAB-2023b-r6.eb
For 	INC1471579
Build: `alsa-lib-1.2.10.eb`
then...
`MATLAB-2023b-r6.eb --module-only`
Default:
> Matlab-2023-alsa

- easyconfigs/p/pyglotaran/pyglotaran-0.7.2-foss-2022a.eb
For INC1466327- `pyglotaran-0.7.2-foss-2022a.eb`
Default:
**Note:** dependency attrs is already a Python dependency version 21.4.0, pyglotaran requires attrs >= 22.1.0
> pyglotaran app install for INC1466327

- easyconfigs/t/TIMP/TIMP-1.13.6-foss-2022a-R-4.2.3.eb
For INC1466327 - `TIMP-1.13.6-foss-2022a-R-4.2.3.eb`
Default:
> TIMP for INC1466327

- easyconfigs/c/Check/Check-0.15.2-GCCcore-12.2.0.eb
- easyconfigs/s/snp-sites/snp-sites-2.5.1-GCCcore-12.2.0.eb
For INC1466564 - `Check-0.15.2-GCCcore-12.2.0.eb snp-sites-2.5.1-GCCcore-12.2.0.eb`
Default:
> snp-sites app plus Check for INC1466564

- easyconfigs/o/OpenLB/OpenLB-1.6.0-foss-2022a.eb
For INC1466030 - `OpenLB-1.6.0-foss-2022a.eb`
Default:
> additional configuration + Makefile

- easyconfigs/b/BEAR-R-bio/BEAR-R-bio-2022b-foss-2022b-R-4.3.1.eb
- easyconfigs/h/hdWGCNA/hdWGCNA-20240201-foss-2022b-R-4.3.1.eb
For INC1468886 - `hdWGCNA-20240201-foss-2022b-R-4.3.1.eb`
Default:
> hdWGCNA extension

- easyconfigs/t/tax_myPHAGE/taxmyphage-0.2.7-foss-2022b.eb
For INC1465929 - `taxmyphage-0.2.7-foss-2022b.eb`
**Notes**:
1. I chopped out the restrictive poetry deps
2. Although the users can simply download the databases, i've downloaded a copy and placed in $BB_APPS_DATA/taxmyphage. This is sl-d to the installdir.
Default:
> taxmyphage

- easyconfigs/a/AdmixTools/AdmixTools-7.0.2-foss-2022b-R-4.3.1-Perl-5.36.0.eb
- easyconfigs/a/AdmixTools/AdmixTools_makefile.patch
For INC1468480 - `AdmixTools-7.0.2-foss-2022b-R-4.3.1-Perl-5.36.0.eb`
Default:
> AdmixTools easyconf and patch

- easyconfigs/a/AdmixTools/AdmixTools-7.0.2-foss-2022b-R-4.3.1-Perl-5.36.0.eb
> GSL is a dep of R

- easyconfigs/q/QIIME2/QIIME2-2024.2.eb
For INC1473876- `QIIME2-2024.2.eb`
Default:
>  QIIME2.2024.2 

- easyconfigs/v/VASP/VASP-6.4.2-intel-2022a-DFT-D4.eb
- easyconfigs/v/VASP/VASP-6.4.2_add-DFT-D4.patch
For INC1477702
`VASP-6.4.2-intel-2022a-DFT-D4.eb`:
> VASP with DFT-D4

- easyconfigs/a/AlphaFold/AlphaFold-2.3.2-foss-2022a-CUDA-11.7.0.eb
- easyconfigs/a/AlphaFold/AlphaFold-2.3.2-foss-2022a.eb
- easyconfigs/a/AlphaFold/AlphaFold-2.3.2_data-dep-paths.patch
- easyconfigs/a/AlphaFold/AlphaFold-2.3.2_use_openmm_7.7.0.patch
For INC1484174
`AlphaFold-2.3.2-foss-2022a.eb`:
`AlphaFold-2.3.2-foss-2022a-CUDA-11.7.0.eb`:
> AlphaFold 2.3.2

- easyconfigs/l/LABRAT/LABRAT-0.3.0-foss-2022a.eb
For INC1486735- `LABRAT-0.3.0-foss-2022a.eb`
Default:
> LABRAT app install for INC1486735

- .github/workflows/flake8.yml
- easyconfigs/b/BEAR-R-bio/BEAR-R-bio-2022b-foss-2022b-R-4.3.1.eb
- easyconfigs/d/digitalDLSorteR/digitalDLSorteR-1.0.1-foss-2022b-R-4.3.1.eb
For INC1487268 - `digitalDLSorteR-1.0.1-foss-2022b-R-4.3.1.eb BEAR-R-bio-2022b-foss-2022b-R-4.3.1.eb`
Default:
> digitalDLSorteR for INC1487268

- easyconfigs/m/MetaCortex/MetaCortex-64095a8-GCCcore-12.2.0.eb
For INC1493329 - `MetaCortex-64095a8-GCCcore-12.2.0.eb`
Default:
> MetaCortex

- easyconfigs/v/vcfstats/vcfstats-0.6.0-foss-2022b.eb
For  INC1501806 - `vcfstats-0.6.0-foss-2022b.eb`
Default:
> vcfstats app install for INC1501806

- easyconfigs/v/vcfstats/vcfstats-0.6.0-foss-2022b.eb
> fix cyvcf2 install

- easyconfigs/i/IRkernel/IRkernel-1.3.2-gfbf-2023a-R-4.4.1.eb
For internal - `IRkernel-1.3.2-gfbf-2023a-R-4.4.1.eb`
Default:
> IRkernel for R 4.4.1

- easyconfigs/b/BEAR-R-bio/BEAR-R-bio-2023a-foss-2023a-R-4.4.1.eb
> Add BEAR R bio

- easyconfigs/e/edk/edk-2.1.1.0.eb
For INC1506485 - `edk-2.1.1.0.eb`
Default:
> edk 2.1.1.0

- easyconfigs/p/PyTorch3D/PyTorch3D-0.7.5-foss-2022b-CUDA-12.0.0.eb
- easyconfigs/t/torchvision/torchvision-0.16.0-foss-2022a-CUDA-12.0.0.eb
For INC1508572 - `torchvision-0.16.0-foss-2022a-CUDA-12.0.0.eb PyTorch3D-0.7.5-foss-2022b-CUDA-12.0.0.eb`
Default:
> PyTorch3D and torchvision for INC1508572

- easyconfigs/i/InterProScan/InterProScan-5.68-100.0-foss-2023a.eb
For INC1509061 - `InterProScan-5.68-100.0-foss-2023a.eb`
Default:
> build:interProScan

- easyconfigs/l/LAMMPS-MACE/LAMMPS-MACE-20240201-foss-2022b-CUDA-12.0.0.eb
For INC1504123
`LAMMPS-MACE-20240201-foss-2022b-CUDA-12.0.0.eb`:
> LAMMPS-MACE

- easyconfigs/u/UMI-VarCal/UMI-VarCal-2.8.2-foss-2022b.eb
- easyconfigs/u/UMI-VarCal/umi_varcal_func_path.patch
- easyconfigs/u/UMI-VarCal/umi_varcal_readme_path.patch
For INC1504147 - `UMI-VarCal-2.8.2-foss-2022b.eb`
Default:
> UMI-VarCal app install INC1504147

- easyconfigs/p/PlotMS/PlotMS-6.2.0-GCC-12.2.0.eb
- easyconfigs/q/QCxMS/QCxMS-5.2.1-gfbf-2022b.eb
- easyconfigs/q/QCxMS/QCxMS-5.2.1_meson-linking.patch
- easyconfigs/t/tblite/tblite-0.2.1-gfbf-2022b.eb
For INC1509805
`QCxMS-5.2.1-gfbf-2022b.eb PlotMS-6.2.0-GCC-12.2.0.eb`:
> QCxMS and PlotMS

- easyconfigs/o/OpenMC/OpenMC-0.14.0-foss-2022b.eb
For INC1511711 - `OpenMC-0.14.0-foss-2022b.eb`
These changes have aleady been deployed manually so there's no need to rebuild.
> OpenMC: Create symlink so that scripts can locate lib

- easyconfigs/m/MNE-Python/MNE-Python-1.7.1-foss-2023a.eb
For INC1512293 - `MNE-Python-1.7.1-foss-2023a.eb`
Default:
> MNE-Python 1.7.1

- easyconfigs/e/earthpy/earthpy-0.9.4-foss-2023a.eb
For INC1514364 - `earthpy-0.9.4-foss-2023a.eb`
Default:
> earthpy easyconf

- easyconfigs/c/Cellphy/Cellphy-0.9.2-foss-2022b.eb
- easyconfigs/c/Cellphy/Cellphy_modify_paths.patch
For INC1508101 - `Cellphy-0.9.2-foss-2022b.eb`
Default:
> Cellphy install for INC1508101

- easyconfigs/g/gffutils/gffutils-0.12-foss-2022a.eb
- easyconfigs/p/panaroo/panaroo-1.5.0-foss-2022a.eb
For INC1508361- `panaroo-1.5.0-foss-2022a.eb`
Default:
> build:panaroo

- easyconfigs/f/fastahack/fastahack-1.0.0-GCCcore-12.2.0.eb
- easyconfigs/f/fermi-lite/fermi-lite-20190320-GCCcore-12.2.0.eb
- easyconfigs/f/filevercmp/filevercmp-20191210-GCCcore-12.2.0.eb
- easyconfigs/f/freebayes/freebayes-1.3.8-foss-2022b-R-4.3.1.eb
- easyconfigs/f/freebayes/freebayes-1.3.8_fix-includes.patch
- easyconfigs/f/freebayes/freebayes-1.3.8_fix-meson.patch
- easyconfigs/f/fsom/fsom-20151117-GCCcore-12.2.0.eb
- easyconfigs/i/intervaltree/intervaltree-0.1-GCCcore-12.2.0.eb
- easyconfigs/m/multichoose/multichoose-1.0.3-GCCcore-12.2.0.eb
- easyconfigs/s/SSW/SSW-1.1-GCCcore-12.2.0.eb
- easyconfigs/s/SeqLib/SeqLib-1.2.0-GCC-12.2.0.eb
- easyconfigs/s/smithwaterman/smithwaterman-20160702-GCCcore-12.2.0.eb
- easyconfigs/t/tabixpp/tabixpp-1.1.2-GCC-12.2.0.eb
- easyconfigs/v/VEP/VEP-112-GCC-12.2.0.eb
- easyconfigs/v/vcflib/vcflib-1.0.9-foss-2022b-R-4.3.1.eb
- easyconfigs/w/WFA2/WFA2-2.3.3-GCCcore-12.2.0.eb
For RTASK0191890 and RTASK0192059
Default:
> VEP and freebayes (and deps)

- easyconfigs/e/earthengine-api/earthengine-api-0.1.413-foss-2023a.eb
- easyconfigs/r/rasterstats/rasterstats-0.19.0-foss-2023a.eb
- easyconfigs/s/sentinelsat/sentinelsat-1.2.1-GCCcore-12.3.0.eb
For INC1514364
`eb earthengine-api-0.1.413-foss-2023a.eb rasterstats-0.19.0-foss-2023a.eb sentinelsat-1.2.1-GCCcore-12.3.0.eb -r -T`
Further info
- `earthengine-api-0.1.413-foss-2023a.eb`: new easyconf
- `rasterstats-0.19.0-foss-2023a.eb`: modified from older upstream version
- `sentinelsat-1.2.1-GCCcore-12.3.0.eb`: modified from older upstream version
Default:
> INC1514364 various

- easyconfigs/g/GenomeTools/GenomeTools-1.6.5-GCC-12.2.0.eb
- easyconfigs/g/GenomeTools/GenomeTools-1.6.5-GCC-12.3.0.eb
For INC1514444 - `GenomeTools-1.6.5-GCC-12.3.0.eb`
Default:
> Genometools

- easyconfigs/i/ipykernel/ipykernel-6.25.0-GCCcore-12.2.0.eb
For INC1516149 - `ipykernel-6.25.0-GCCcore-12.2.0.eb`
Default:
> ipykernel module for 2022b re JupyterLab

- easyconfigs/e/EarlGrey/EarlGrey-4.4.0.eb
For INC1515734 - `EarlGrey-4.4.0.eb`
Default:
> EarlGrey for INC1515734

- easyconfigs/p/pblat/pblat-2.5.1-foss-2022a.eb
- easyconfigs/s/StringTie/StringTie-2.2.1-GCC-11.3.0.eb
for #446 (and already built as part of #446).
> match htslib version to that used in rest of deps

- easyconfigs/e/EDTA/EDTA-2.2.0.eb
For INC1515734 - `EDTA-2.2.0.eb`
Default:
> EDTA app for INC1515734

- easyconfigs/e/EDTA/EDTA-2.2.0.eb
For INC1515734 - `EDTA-2.2.0.eb`
Default:
**Note:** Tis is a rebuild
> Fix homepage and desciption in EDTA

- easyconfigs/n/Newton-X/Newton-X-2.6-b01-GCCcore-12.3.0.eb
For INC1519093 - `Newton-X-2.6-b01-GCCcore-12.3.0.eb`
Default:
> Newton-X easyconf

- easyconfigs/n/Newton-X/Newton-X-2.6-b01-GCCcore-12.3.0.eb
For INC1519093 - `Newton-X-2.6-b01-GCCcore-12.3.0.eb`
Default:
> Run tests in postinstall to ensure install directory exists

- easyconfigs/p/Pympler/Pympler-1.1-GCCcore-12.3.0.eb
For INC1522882 - `Pympler-1.1-GCCcore-12.3.0.eb`
Default:
> Easyconf for Pympler-1.1

- easyconfigs/a/AdmixTools/AdmixTools-8.0.2-foss-2023a-R-4.4.1-Perl-5.36.1.eb
- easyconfigs/a/AdmixTools/AdmixTools802_makefile.patch
For INC1539472 - `AdmixTools-8.0.2-foss-2023a-R-4.4.1-Perl-5.36.1.eb`
Default:
> build(AdmixTools802): installation reproduced

- easyconfigs/e/EIGENSOFT/EIGENSOFT-8.0.0-foss-2023a.eb
- easyconfigs/e/EIGENSOFT/EIGENSOFT-8.0.0_flexiblas.patch
For INC1541382 - `EIGENSOFT-8.0.0-foss-2023a.eb`
Default:
> build(EIGENSOFT): using foss 2023a toolchain

- easyconfigs/i/InterProScan/InterProScan-5.70-102.0-foss-2023a.eb
For INC1541711 - `InterProScan-5.70-102.0-foss-2023a.eb`
Default:
> build(interProScan): reproduced, version update 5.70.102

- easyconfigs/c/cads-api-client/cads-api-client-1.5.0-GCCcore-12.3.0.eb
- easyconfigs/c/cdsapi/cdsapi-0.7.4-GCCcore-12.3.0.eb
For INC1549119 - `cdsapi-0.7.4-GCCcore-12.3.0.eb`
Deps:
* `cads-api-client-1.5.0-GCCcore-12.3.0.eb`
Default:
> cdsapi 0.7.4

- easyconfigs/q/QML/QML-0.4.0.27-foss-2022b.eb
- easyconfigs/q/QML/QML-0.4.0.27_fix-setup.py.patch
- easyconfigs/q/QML/QML_frepresentations-fix.patch
For INC1550231- `QML-0.4.0.27-foss-2022b.eb`
Default:
> QML for INC1550231

- easyconfigs/e/EarlGrey/EarlGrey-4.4.0.eb
For INC1553894- `EarlGrey-4.4.0.eb`
Default:
**Note** this is a rebuild
> EarlGrey fix for INC1553894

- easyconfigs/d/DFTB+/DFTB+-23.1-foss-2023a.eb
- easyconfigs/t/tblite/tblite-0.3.0-foss-2023a.eb
For INC1555168
rebuild: `DFTB+-23.1-foss-2023a.eb`:
> add tblite to DFTB+

- easyconfigs/p/python-cdo/python-cdo-1.6.0-foss-2023a.eb
For INC1554581- `python-cdo-1.6.0-foss-2023a.eb`
Default:
> build(python-cdo)

- easyconfigs/n/netron/netron-8.0.2-GCCcore-12.3.0.eb
For INC1554235 - `netron-8.0.2-GCCcore-12.3.0.eb`
Default:
> netron for INC1554235

- easyconfigs/d/defense-finder/defense-finder-1.3.0-foss-2022b.eb
- easyconfigs/s/scikit-build-core/scikit-build-core-0.9.3-GCCcore-12.2.0.eb
For INC1555415
`defense-finder-1.3.0-foss-2022b.eb`:
> defense-finder

- easyconfigs/m/Multiwfn/Multiwfn-3.8-dev-iimkl-2023a.eb
For INC1556890 - `Multiwfn-3.8-dev-iimkl-2023a.eb`
Default:
> Multiwfn for INC1556890

- easyconfigs/b/BNC/BNC-2.13.1-GCCcore-12.3.0.eb
- easyconfigs/c/Chart-Gnuplot/Chart-Gnuplot-0.23-GCCcore-12.3.0.eb
- easyconfigs/d/Date-Manip/Date-Manip-6.95-GCCcore-12.3.0.eb
- easyconfigs/p/PDL/PDL-2.095-GCCcore-12.3.0.eb
- easyconfigs/p/Proc-ProcessTable/Proc-ProcessTable-0.636-GCCcore-12.3.0.eb
For INC1560864 - `BNC-2.13.1-GCCcore-12.3.0.eb`
Default:
> BKG NTRIP Client (BNC) 2.13.1

- easyconfigs/f/Flye/Flye-2.9.5-GCC-12.3.0.eb
For INC1562460  - `Flye-2.9.5-GCC-12.3.0.eb`
Default:
> build(flye): <- modified usptream 2.9.3

- easyconfigs/p/ParaView/ParaView-5.12.1.eb
- easyconfigs/p/ParaView/ParaView-5.13.1.eb
For INC1561725 - `ParaView-5.12.1.eb` - `ParaView-5.13.1.eb`
Default:
> install(ParaView):updates url to binaries 5.12.1 & 5.13.1

- easyblocks/wrfchem.py
- easyconfigs/w/WRF/WRF-4.4-foss-2022a-dmpar-chem.eb
For INC1562467 - `WRF-4.4-foss-2022a-dmpar-chem.eb)`
No need to do a rebuild on this.
> New WRFCHEM easyblock and remove WRF for upstream

- easyconfigs/a/ANSYS/ANSYS-2023R1.eb
- easyconfigs/a/ANSYS/ANSYS-2024R1.eb
Module files have been edited for this change.
> deal with change in slurm behaviour

- easyconfigs/s/ShengBTE/ShengBTE-1.5.1-foss-2023a.eb
- easyconfigs/t/thirdorder/thirdorder-1.1.3-foss-2023a.eb
For INC1565897:
1) `eb ShengBTE-1.5.1-foss-2023a.eb -Tr`
2) `eb thirdorder-1.1.3-foss-2023a.eb -Tr`
Default:
> Shengbte thirdorder

- easyconfigs/p/pod5/pod5-file-format-0.3.23-foss-2023a.eb
- easyconfigs/p/pod5/pod5-file-format-0.3.23_dep_fix.patch
For INC1555138 - `pod5-file-format-0.3.23-foss-2023a.eb`
Default:
> pod5(0.3.23): choose correct interpreter and pybind module version, unpin pyarrow

- easyconfigs/w/WPS/WPS-4.4_netCDF-Fortran_separate_path.patch
- easyconfigs/w/WPS/WPS-4.5-foss-2023a-dmpar.eb
- easyconfigs/w/WPS/WPS-4.6.0_fix_jasper_decode.patch
For INC1562464 - `WPS-4.5-foss-2023a-dmpar.eb`
Default:
> WPS for INC1562464

- easyconfigs/b/baysor/baysor-0.7.1-linux-x86_64.eb
For INC1572202:
`time eb baysor-0.7.1-linux-x86_64.eb -Tr`
Default:
> baysor 0.7.1

- easyconfigs/b/BEDTools/BEDTools-2.31.1-GCC-12.3.0.eb
- easyconfigs/b/Bowtie2/Bowtie2-2.5.4-GCC-12.3.0.eb
- easyconfigs/g/gawk/gawk-5.3.1-GCC-12.3.0.eb
- easyconfigs/h/hostile/hostile-2.0.0-foss-2023a.eb
- easyconfigs/m/minimap2/minimap2-2.28-GCCcore-12.3.0.eb
- easyconfigs/p/python-isal/python-isal-1.6.1-GCCcore-12.3.0.eb
- easyconfigs/s/SAMtools/SAMtools-1.21-GCC-12.3.0.eb
For INC1575771 / INC1575825
Default:
> hostile and deps

- easyconfigs/m/mpi4py/mpi4py-3.1.4-iimpi-2023a.eb
- easyconfigs/n/netcdf4-python/netcdf4-python-1.6.4-intel-2023a.eb
For INC1579774 - `netcdf4-python-1.6.4-intel-2023a.eb`
Default:
> netcdf4-python - Intel version

- easyconfigs/t/Thermo-Calc/Thermo-Calc-2025a-foss-2023a.eb
For INC1574811 - `Thermo-Calc-2025a-foss-2023a.eb`
Default:
> Thermo-Calc 2025a

- easyconfigs/t/Thermo-Calc/Thermo-Calc-2025a-foss-2023a.eb
For INC1574811 - `Thermo-Calc-2025a-foss-2023a.eb`
> Update checksum for rebuilt tar file

- easyconfigs/r/RELION/RELION-4.0.0_add_bham_submit_file_args.patch
- easyconfigs/r/RELION/relion_sbatch.sh
> relion patches

- easyblocks/ansysem.py
- easyconfigs/a/ANSYSEM/ANSYSEM-2024R2.eb
For INC1561450 - `ANSYSEM-2024R2.eb`
N.B. the easyblock changes here are _NOT_ backwards compatible with earlier ANSYSEM installers.
Default:
> ANSYS EM 2024R2

- easyconfigs/g/GPAW/GPAW-24.1.0-foss-2023a.eb
For INC1571921- `GPAW-24.1.0-foss-2023a.eb`
Default:
> GPAW for INC1571921

- easyconfigs/s/SemiBin/SemiBin-2.1.0-foss-2023a-CUDA-12.1.1.eb
- easyconfigs/s/SemiBin/SemiBin-2.1.0-foss-2023a.eb
For INC1582599
`SemiBin-2.1.0-foss-2023a.eb`:
`SemiBin-2.1.0-foss-2023a-CUDA-12.1.1.eb`:
> Semibin-2.1.0

- easyconfigs/c/cds_insertion/cds_insertion-0.1dev-20240521-foss-2023a.eb
> permissions

- easyconfigs/k/Kent_tools/Kent_tools-478-GCC-12.3.0.eb
For INC1588290
`eb Kent_tools-478-GCC-12.3.0.eb -Tr`:
> Kent_tools

- easyconfigs/t/Transformers/Transformers-4.39.3-foss-2023a-CUDA-12.1.1.eb
- easyconfigs/t/Transformers/Transformers-4.39.3-foss-2023a.eb
For INC1586631 - `Transformers-4.39.3-foss-2023a.eb`
Default:
`Transformers-4.39.3-foss-2023a-CUDA-12.1.1.eb`
> Transofrmers install for INC1586631

- easyconfigs/n/NanoPlot/NanoPlot-1.43.0-foss-2023a.eb
For INC1587407 - `NanoPlot-1.43.0-foss-2023a.eb`
Default:
> build(NanoPlot): upstream ec

- easyconfigs/p/python-box/python-box-7.3.2-GCCcore-12.3.0.eb
For INC1588141 - `python-box-7.3.2-GCCcore-12.3.0.eb`
Default:
> build(python-box)

- easyconfigs/c/CUDA-Python/CUDA-Python-12.1.0-gfbf-2023a-CUDA-12.1.1.eb
- easyconfigs/r/RAPIDS/RAPIDS-24.4-foss-2023a-CUDA-12.1.1.eb
For INC1586914 - `RAPIDS-24.4-foss-2023a-CUDA-12.1.1.eb`
All from upstream
**N.B. requires GPU node for building**
> RAPIDS Easyconf and deps

- easyconfigs/c/CellRanger/CellRanger-9.0.1.eb
For INC1584581- `CellRanger-9.0.1.eb`
Default:
> build(cellranger)

- easyconfigs/i/ichorCNA/ichorCNA-0.3.2-20191219-foss-2023a-R-4.4.1.eb
- easyconfigs/i/ichorCNA/ichorCNA-0.3.2-20191219-foss-2023a.eb
For INC1587061 - `ichorCNA-0.3.2-20191219-foss-2023a.eb`
Default:
> build(ichorCNA)

- easyconfigs/i/IJulia/IJulia-1.26.0-Julia-1.11.4.eb
- easyconfigs/j/Julia/Julia-1.11.4-linux-x86_64.eb
For INC1593232 - `Julia-1.11.4-linux-x86_64.eb IJulia-1.26.0-Julia-1.11.4.eb`
Default:
> Julia and IJulia for INC1593232

- easyconfigs/s/SciTools-Iris/SciTools-Iris-3.12.0-foss-2023a.eb
For INC1591699
`SciTools-Iris-3.12.0-foss-2023a.eb`:
> SciTools-Iris

- easyconfigs/b/bcbio-gff/bcbio-gff-0.7.1-foss-2023a.eb
- easyconfigs/c/CMSeq/CMSeq-1.0.4-foss-2023a.eb
- easyconfigs/h/humann/humann-4.0.0a1-foss-2023a.eb
- easyconfigs/m/MetaPhlAn/MetaPhlAn-4.1.1-foss-2023a.eb
- easyconfigs/p/PhyloPhlAn/PhyloPhlAn-3.1.1-foss-2023a.eb
- easyconfigs/s/SEPP/SEPP-4.5.5-foss-2023a.eb
For INC1588340 - `humann-4.0.0a1-foss-2023a.eb`
Default:
> build(humann)

- easyconfigs/f/figeno/figeno-1.6.6-foss-2023a.eb
For INC1596195 - `figeno-1.6.6-foss-2023a.eb`
Default:
> figeno install for INC1596195

- easyconfigs/v/VASPKIT/VASPKIT-1.5.1-foss-2023a.eb
> fix checksum

- easyconfigs/l/LTR_retriever/LTR_retriever-3.0.1-foss-2023a.eb
- easyconfigs/r/RECON/RECON-1.08-GCC-12.3.0.eb
- easyconfigs/r/RepeatModeler/RepeatModeler-2.0.6-foss-2023a.eb
- easyconfigs/r/RepeatScout/RepeatScout-1.0.7-GCC-12.3.0.eb
- easyconfigs/t/TWL-NINJA/TWL-NINJA-1.00-cluster_only-GCC-12.3.0.eb
For INC1599782 - `RepeatModeler-2.0.6-foss-2023a.eb`
Almost verbatim from: <https://github.com/easybuilders/easybuild-easyconfigs/pull/22250>
- Using our existing GenomeTools build
- Added `chmod +x` postinstall to RepeatScout (re failing check in RepeatModeler)
Default:
> RepeatModeler (and RepeatMasker)

- easyconfigs/v/visdom/visdom-0.2.4-gfbf-2023a.eb
For INC1600561 - `visdom-0.2.4-gfbf-2023a.eb`
Default:
> Update visdom easyconfig sanity check with command that creates fonts dir

- easyconfigs/x/Xenium-Ranger/Xenium-Ranger-3.1.1.eb
For INC1600912 - `Xenium-Ranger-3.1.1.eb`
Default:
> xeniumranger easyconf

- easyconfigs/q/QIIME2/QIIME2-2025.4.eb
For INC1602514 - `QIIME2-2025.4.eb`
(Slight change to sources from our previous version.)
Default:
> QIIME2-2025.4 easyconf update

- easyconfigs/p/Paragraph/Paragraph-2.4a-GCC-11.3.0.eb
- easyconfigs/p/Paragraph/Paragraph-v2.4a_boostStaticLibOFF.patch
- easyconfigs/p/Paragraph/Paragraph-v2.4a_graphtoolsLimitsHeader.patch
For INC1600598 - `Paragraph-2.4a-GCC-11.3.0.eb`
Default:
> build(paragraph): completes

- easyconfigs/t/TempestExtremes/TempestExtremes-2.3.1-foss-2023a.eb
For INC1605573:
`eb TempestExtremes-2.3.1-foss-2023a.eb -r`
Default:
> TempestExtremes

- easyconfigs/f/fseq2/fseq2-2.0.4-foss-2024a.eb
- easyconfigs/p/pyBigWig/pyBigWig-0.3.24-gfbf-2024a.eb
- easyconfigs/p/pybedtools/pybedtools-0.11.0-foss-2024a.eb
For  INC1615561 - `pyBigWig-0.3.24-gfbf-2024a.eb pybedtools-0.11.0-foss-2024a.eb fseq2-2.0.4-foss-2024a.eb`
Default:
> Fseq2 for INC1615561

- easyconfigs/c/CST-Studio-Suite/CST-Studio-Suite-2025.SP5-GCCcore-12.3.0-Java-17.eb
For INC1615928 - `CST-Studio-Suite-2025.SP5-GCCcore-12.3.0-Java-17.eb`
Default:
> CST 2025.SP5

- easyconfigs/b/BEAR-R-bio/BEAR-R-bio-2024a-foss-2024a-R-4.5.0.eb
`BEAR-R-bio-2024a-foss-2024a-R-4.5.0.eb`
Default:
> Add BEAR-R-bio 2024a

- easyconfigs/i/IRkernel/IRkernel-1.3.2-gfbf-2024a-R-4.5.0.eb
- easyconfigs/i/ipykernel/ipykernel-6.29.5-GCCcore-13.3.0.eb
- easyconfigs/i/ipykernel/jupyter-core-5.7.2_fix_jupyter_path.patch
`IRkernel-1.3.2-gfbf-2024a-R-4.5.0.eb ipykernel-6.29.5-GCCcore-13.3.0.eb`
Default:
> Updated kernels for JupyterLab app

- easyconfigs/d/Dsuite/Dsuite-20241219-GCC-13.3.0.eb
- easyconfigs/d/Dsuite/Dsuite-20241219-intel-compilers-2024.2.0.eb
For INC1618531 - `Dsuite-20241219-GCC-13.3.0.eb` 
`Dsuite-20241219-intel-compilers-2024.2.0.eb`
Default:
> build: Dsuite GCC + Intel compilers

- easyconfigs/p/picard/picard-3.4.0-Java-17.eb
For INC1618298 - `picard-3.4.0-Java-17.eb`
Default:
> build: picard 3.4.0 java 17

- easyconfigs/f/FourPhonon/FourPhonon-1.2-intel-2023a.eb
For INC1619462 - `FourPhonon-1.2-intel-2023a.eb`
Default:
> INC1619462 FourPhonon-1.2-intel-2023a.eb

- easyconfigs/m/MiXCR/MiXCR-4.7.0-Java-17.eb
For INC1621206 - `MiXCR-4.7.0-Java-17.eb`
4.7.0 specifically requested by user (4.6.0 upstream)
Default:
> MiXCR 4.7.0

- easyconfigs/t/Thermo-Calc/Thermo-Calc-2025b-foss-2024a.eb
For INC1621614 - `Thermo-Calc-2025b-foss-2024a.eb`
Default:
> ThermoCalc 2025b

- easyconfigs/h/Harminv/Harminv-1.4.2-foss-2023a.eb
- easyconfigs/l/libGDSII/libGDSII-0.21-GCCcore-12.3.0.eb
- easyconfigs/l/libctl/libctl-4.5.1-GCCcore-12.3.0.eb
- easyconfigs/m/MPB/MPB-1.12.0-foss-2023a.eb
- easyconfigs/m/Meep/Meep-1.30.1-foss-2023a.eb
For INC1622381/INC1622380 - `Meep-1.30.1-foss-2023a.eb`
Default:
> Meep 1.30.1 and MPB 1.12.0

- easyconfigs/p/PoreBlazer/PoreBlazer-4-GCCcore-13.3.0.eb
For INC1623205 - `PoreBlazer-4-GCCcore-13.3.0.eb`
Default:
> PoreBlazer 4 easyconf

- easyconfigs/s/SHAPEIT5/SHAPEIT5-5.1.1-foss-2024a-20240315.eb
For INC1627283 - `SHAPEIT5-5.1.1-foss-2024a-20240315.eb`
Default:
> build(shapeit5): namespace resolution fixed in recent commit

- easyconfigs/e/e3nn/e3nn-0.4.4-foss-2023a-CUDA-12.1.1.eb
- easyconfigs/m/MACE/MACE-0.3.14-foss-2023a-CUDA-12.1.1-ASE-3.24.0.eb
For INC1631334 - `MACE-0.3.14-foss-2023a-CUDA-12.1.1-ASE-3.24.0.eb`
Modified from:
- <https://github.com/easybuilders/easybuild-easyconfigs/pull/23210>
- <https://github.com/easybuilders/easybuild-easyconfigs/pull/23660>
Default:
> MACE and deps

- easyconfigs/n/nanomonsv/nanomonsv-0.8.0-foss-2023a.eb
For INC1635678
Full rebuild to ensure that all deps are created:
```
eb nanomonsv-0.8.0-foss-2023a.eb -r --rebuild
```
Default:
> nanomonsv full set of deps

- easyconfigs/b/Bandage/Bandage-0.8.1-gompi-2023a.eb
For INC1636353 - `Bandage-0.8.1-gompi-2023a.eb`
Default:
> Bandage 0.8.1

- easyconfigs/a/ARACNe-AP/ARACNe-AP-20180412-Java-11.eb
For INC1636802 - `ARACNe-AP-20180412-Java-11.eb`
Default:
> ARACNe-AP easyconf

- easyconfigs/c/CellBender/CellBender-0.3.2-foss-2023a.eb
For INC1631583 - `CellBender-0.3.2-foss-2023a.eb`
Default:
> fix(CellBender): checksums
